'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.1
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System.Runtime.Serialization

'
'This code was auto-generated by Microsoft.Silverlight.ServiceReference, version 4.0.50826.0
'
Namespace GeocodeServiceReference
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="RequestBase", [Namespace]:="http://dev.virtualearth.net/webservices/v1/common"),  _
     System.Runtime.Serialization.KnownTypeAttribute(GetType(GeocodeServiceReference.ReverseGeocodeRequest)),  _
     System.Runtime.Serialization.KnownTypeAttribute(GetType(GeocodeServiceReference.GeocodeRequest))>  _
    Partial Public Class RequestBase
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private CredentialsField As Microsoft.Maps.MapControl.Credentials
        
        Private CultureField As String
        
        Private ExecutionOptionsField As GeocodeServiceReference.ExecutionOptions
        
        Private UserProfileField As GeocodeServiceReference.UserProfile
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Credentials() As Microsoft.Maps.MapControl.Credentials
            Get
                Return Me.CredentialsField
            End Get
            Set
                If (Object.ReferenceEquals(Me.CredentialsField, value) <> true) Then
                    Me.CredentialsField = value
                    Me.RaisePropertyChanged("Credentials")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Culture() As String
            Get
                Return Me.CultureField
            End Get
            Set
                If (Object.ReferenceEquals(Me.CultureField, value) <> true) Then
                    Me.CultureField = value
                    Me.RaisePropertyChanged("Culture")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property ExecutionOptions() As GeocodeServiceReference.ExecutionOptions
            Get
                Return Me.ExecutionOptionsField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ExecutionOptionsField, value) <> true) Then
                    Me.ExecutionOptionsField = value
                    Me.RaisePropertyChanged("ExecutionOptions")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property UserProfile() As GeocodeServiceReference.UserProfile
            Get
                Return Me.UserProfileField
            End Get
            Set
                If (Object.ReferenceEquals(Me.UserProfileField, value) <> true) Then
                    Me.UserProfileField = value
                    Me.RaisePropertyChanged("UserProfile")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="ExecutionOptions", [Namespace]:="http://dev.virtualearth.net/webservices/v1/common")>  _
    Partial Public Class ExecutionOptions
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private SuppressFaultsField As Boolean
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property SuppressFaults() As Boolean
            Get
                Return Me.SuppressFaultsField
            End Get
            Set
                If (Me.SuppressFaultsField.Equals(value) <> true) Then
                    Me.SuppressFaultsField = value
                    Me.RaisePropertyChanged("SuppressFaults")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="UserProfile", [Namespace]:="http://dev.virtualearth.net/webservices/v1/common"),  _
     System.Runtime.Serialization.KnownTypeAttribute(GetType(Microsoft.Maps.MapControl.LocationRect)),  _
     System.Runtime.Serialization.KnownTypeAttribute(GetType(GeocodeServiceReference.Circle)),  _
     System.Runtime.Serialization.KnownTypeAttribute(GetType(GeocodeServiceReference.Polygon))>  _
    Partial Public Class UserProfile
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private CurrentHeadingField As GeocodeServiceReference.Heading
        
        Private CurrentLocationField As GeocodeServiceReference.UserLocation
        
        Private DeviceTypeField As GeocodeServiceReference.DeviceType
        
        Private DistanceUnitField As GeocodeServiceReference.DistanceUnit
        
        Private IPAddressField As String
        
        Private MapViewField As Microsoft.Maps.MapControl.ShapeBase
        
        Private ScreenSizeField As GeocodeServiceReference.SizeOfint
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property CurrentHeading() As GeocodeServiceReference.Heading
            Get
                Return Me.CurrentHeadingField
            End Get
            Set
                If (Object.ReferenceEquals(Me.CurrentHeadingField, value) <> true) Then
                    Me.CurrentHeadingField = value
                    Me.RaisePropertyChanged("CurrentHeading")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property CurrentLocation() As GeocodeServiceReference.UserLocation
            Get
                Return Me.CurrentLocationField
            End Get
            Set
                If (Object.ReferenceEquals(Me.CurrentLocationField, value) <> true) Then
                    Me.CurrentLocationField = value
                    Me.RaisePropertyChanged("CurrentLocation")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property DeviceType() As GeocodeServiceReference.DeviceType
            Get
                Return Me.DeviceTypeField
            End Get
            Set
                If (Me.DeviceTypeField.Equals(value) <> true) Then
                    Me.DeviceTypeField = value
                    Me.RaisePropertyChanged("DeviceType")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property DistanceUnit() As GeocodeServiceReference.DistanceUnit
            Get
                Return Me.DistanceUnitField
            End Get
            Set
                If (Me.DistanceUnitField.Equals(value) <> true) Then
                    Me.DistanceUnitField = value
                    Me.RaisePropertyChanged("DistanceUnit")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property IPAddress() As String
            Get
                Return Me.IPAddressField
            End Get
            Set
                If (Object.ReferenceEquals(Me.IPAddressField, value) <> true) Then
                    Me.IPAddressField = value
                    Me.RaisePropertyChanged("IPAddress")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property MapView() As Microsoft.Maps.MapControl.ShapeBase
            Get
                Return Me.MapViewField
            End Get
            Set
                If (Object.ReferenceEquals(Me.MapViewField, value) <> true) Then
                    Me.MapViewField = value
                    Me.RaisePropertyChanged("MapView")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property ScreenSize() As GeocodeServiceReference.SizeOfint
            Get
                Return Me.ScreenSizeField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ScreenSizeField, value) <> true) Then
                    Me.ScreenSizeField = value
                    Me.RaisePropertyChanged("ScreenSize")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="ReverseGeocodeRequest", [Namespace]:="http://dev.virtualearth.net/webservices/v1/geocode"),  _
     System.Runtime.Serialization.KnownTypeAttribute(GetType(GeocodeServiceReference.GeocodeLocation)),  _
     System.Runtime.Serialization.KnownTypeAttribute(GetType(GeocodeServiceReference.UserLocation))>  _
    Partial Public Class ReverseGeocodeRequest
        Inherits GeocodeServiceReference.RequestBase
        
        Private LocationField As Microsoft.Maps.MapControl.Location
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Location() As Microsoft.Maps.MapControl.Location
            Get
                Return Me.LocationField
            End Get
            Set
                If (Object.ReferenceEquals(Me.LocationField, value) <> true) Then
                    Me.LocationField = value
                    Me.RaisePropertyChanged("Location")
                End If
            End Set
        End Property
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="GeocodeRequest", [Namespace]:="http://dev.virtualearth.net/webservices/v1/geocode")>  _
    Partial Public Class GeocodeRequest
        Inherits GeocodeServiceReference.RequestBase
        
        Private AddressField As GeocodeServiceReference.Address
        
        Private OptionsField As GeocodeServiceReference.GeocodeOptions
        
        Private QueryField As String
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Address() As GeocodeServiceReference.Address
            Get
                Return Me.AddressField
            End Get
            Set
                If (Object.ReferenceEquals(Me.AddressField, value) <> true) Then
                    Me.AddressField = value
                    Me.RaisePropertyChanged("Address")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Options() As GeocodeServiceReference.GeocodeOptions
            Get
                Return Me.OptionsField
            End Get
            Set
                If (Object.ReferenceEquals(Me.OptionsField, value) <> true) Then
                    Me.OptionsField = value
                    Me.RaisePropertyChanged("Options")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Query() As String
            Get
                Return Me.QueryField
            End Get
            Set
                If (Object.ReferenceEquals(Me.QueryField, value) <> true) Then
                    Me.QueryField = value
                    Me.RaisePropertyChanged("Query")
                End If
            End Set
        End Property
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="Address", [Namespace]:="http://dev.virtualearth.net/webservices/v1/common")>  _
    Partial Public Class Address
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private AddressLineField As String
        
        Private AdminDistrictField As String
        
        Private CountryRegionField As String
        
        Private DistrictField As String
        
        Private FormattedAddressField As String
        
        Private LocalityField As String
        
        Private PostalCodeField As String
        
        Private PostalTownField As String
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property AddressLine() As String
            Get
                Return Me.AddressLineField
            End Get
            Set
                If (Object.ReferenceEquals(Me.AddressLineField, value) <> true) Then
                    Me.AddressLineField = value
                    Me.RaisePropertyChanged("AddressLine")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property AdminDistrict() As String
            Get
                Return Me.AdminDistrictField
            End Get
            Set
                If (Object.ReferenceEquals(Me.AdminDistrictField, value) <> true) Then
                    Me.AdminDistrictField = value
                    Me.RaisePropertyChanged("AdminDistrict")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property CountryRegion() As String
            Get
                Return Me.CountryRegionField
            End Get
            Set
                If (Object.ReferenceEquals(Me.CountryRegionField, value) <> true) Then
                    Me.CountryRegionField = value
                    Me.RaisePropertyChanged("CountryRegion")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property District() As String
            Get
                Return Me.DistrictField
            End Get
            Set
                If (Object.ReferenceEquals(Me.DistrictField, value) <> true) Then
                    Me.DistrictField = value
                    Me.RaisePropertyChanged("District")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property FormattedAddress() As String
            Get
                Return Me.FormattedAddressField
            End Get
            Set
                If (Object.ReferenceEquals(Me.FormattedAddressField, value) <> true) Then
                    Me.FormattedAddressField = value
                    Me.RaisePropertyChanged("FormattedAddress")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Locality() As String
            Get
                Return Me.LocalityField
            End Get
            Set
                If (Object.ReferenceEquals(Me.LocalityField, value) <> true) Then
                    Me.LocalityField = value
                    Me.RaisePropertyChanged("Locality")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property PostalCode() As String
            Get
                Return Me.PostalCodeField
            End Get
            Set
                If (Object.ReferenceEquals(Me.PostalCodeField, value) <> true) Then
                    Me.PostalCodeField = value
                    Me.RaisePropertyChanged("PostalCode")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property PostalTown() As String
            Get
                Return Me.PostalTownField
            End Get
            Set
                If (Object.ReferenceEquals(Me.PostalTownField, value) <> true) Then
                    Me.PostalTownField = value
                    Me.RaisePropertyChanged("PostalTown")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="GeocodeOptions", [Namespace]:="http://dev.virtualearth.net/webservices/v1/geocode")>  _
    Partial Public Class GeocodeOptions
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private CountField As System.Nullable(Of Integer)
        
        Private FiltersField As System.Collections.ObjectModel.ObservableCollection(Of GeocodeServiceReference.FilterBase)
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Count() As System.Nullable(Of Integer)
            Get
                Return Me.CountField
            End Get
            Set
                If (Me.CountField.Equals(value) <> true) Then
                    Me.CountField = value
                    Me.RaisePropertyChanged("Count")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Filters() As System.Collections.ObjectModel.ObservableCollection(Of GeocodeServiceReference.FilterBase)
            Get
                Return Me.FiltersField
            End Get
            Set
                If (Object.ReferenceEquals(Me.FiltersField, value) <> true) Then
                    Me.FiltersField = value
                    Me.RaisePropertyChanged("Filters")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="Heading", [Namespace]:="http://dev.virtualearth.net/webservices/v1/common")>  _
    Partial Public Class Heading
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private OrientationField As Double
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Orientation() As Double
            Get
                Return Me.OrientationField
            End Get
            Set
                If (Me.OrientationField.Equals(value) <> true) Then
                    Me.OrientationField = value
                    Me.RaisePropertyChanged("Orientation")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="UserLocation", [Namespace]:="http://dev.virtualearth.net/webservices/v1/common")>  _
    Partial Public Class UserLocation
        Inherits Microsoft.Maps.MapControl.Location
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private ConfidenceField As GeocodeServiceReference.Confidence
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Confidence() As GeocodeServiceReference.Confidence
            Get
                Return Me.ConfidenceField
            End Get
            Set
                If (Me.ConfidenceField.Equals(value) <> true) Then
                    Me.ConfidenceField = value
                    Me.RaisePropertyChanged("Confidence")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="SizeOfint", [Namespace]:="http://dev.virtualearth.net/webservices/v1/common")>  _
    Partial Public Class SizeOfint
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private HeightField As Integer
        
        Private WidthField As Integer
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Height() As Integer
            Get
                Return Me.HeightField
            End Get
            Set
                If (Me.HeightField.Equals(value) <> true) Then
                    Me.HeightField = value
                    Me.RaisePropertyChanged("Height")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Width() As Integer
            Get
                Return Me.WidthField
            End Get
            Set
                If (Me.WidthField.Equals(value) <> true) Then
                    Me.WidthField = value
                    Me.RaisePropertyChanged("Width")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="Circle", [Namespace]:="http://dev.virtualearth.net/webservices/v1/common"),  _
     System.Runtime.Serialization.KnownTypeAttribute(GetType(GeocodeServiceReference.GeocodeLocation)),  _
     System.Runtime.Serialization.KnownTypeAttribute(GetType(GeocodeServiceReference.UserLocation))>  _
    Partial Public Class Circle
        Inherits Microsoft.Maps.MapControl.ShapeBase
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private CenterField As Microsoft.Maps.MapControl.Location
        
        Private DistanceUnitField As GeocodeServiceReference.DistanceUnit
        
        Private RadiusField As Double
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Center() As Microsoft.Maps.MapControl.Location
            Get
                Return Me.CenterField
            End Get
            Set
                If (Object.ReferenceEquals(Me.CenterField, value) <> true) Then
                    Me.CenterField = value
                    Me.RaisePropertyChanged("Center")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property DistanceUnit() As GeocodeServiceReference.DistanceUnit
            Get
                Return Me.DistanceUnitField
            End Get
            Set
                If (Me.DistanceUnitField.Equals(value) <> true) Then
                    Me.DistanceUnitField = value
                    Me.RaisePropertyChanged("DistanceUnit")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Radius() As Double
            Get
                Return Me.RadiusField
            End Get
            Set
                If (Me.RadiusField.Equals(value) <> true) Then
                    Me.RadiusField = value
                    Me.RaisePropertyChanged("Radius")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="Polygon", [Namespace]:="http://dev.virtualearth.net/webservices/v1/common")>  _
    Partial Public Class Polygon
        Inherits Microsoft.Maps.MapControl.ShapeBase
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private VerticesField As System.Collections.ObjectModel.ObservableCollection(Of Microsoft.Maps.MapControl.Location)
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Vertices() As System.Collections.ObjectModel.ObservableCollection(Of Microsoft.Maps.MapControl.Location)
            Get
                Return Me.VerticesField
            End Get
            Set
                If (Object.ReferenceEquals(Me.VerticesField, value) <> true) Then
                    Me.VerticesField = value
                    Me.RaisePropertyChanged("Vertices")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="DeviceType", [Namespace]:="http://dev.virtualearth.net/webservices/v1/common")>  _
    Public Enum DeviceType As Integer
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        Desktop = 0
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        Mobile = 1
    End Enum
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="DistanceUnit", [Namespace]:="http://dev.virtualearth.net/webservices/v1/common")>  _
    Public Enum DistanceUnit As Integer
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        Kilometer = 0
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        Mile = 1
    End Enum
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="Confidence", [Namespace]:="http://dev.virtualearth.net/webservices/v1/common")>  _
    Public Enum Confidence As Integer
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        High = 0
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        Medium = 1
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        Low = 2
    End Enum
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="GeocodeLocation", [Namespace]:="http://dev.virtualearth.net/webservices/v1/common")>  _
    Partial Public Class GeocodeLocation
        Inherits Microsoft.Maps.MapControl.Location
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private CalculationMethodField As String
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property CalculationMethod() As String
            Get
                Return Me.CalculationMethodField
            End Get
            Set
                If (Object.ReferenceEquals(Me.CalculationMethodField, value) <> true) Then
                    Me.CalculationMethodField = value
                    Me.RaisePropertyChanged("CalculationMethod")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="FilterBase", [Namespace]:="http://dev.virtualearth.net/webservices/v1/geocode"),  _
     System.Runtime.Serialization.KnownTypeAttribute(GetType(GeocodeServiceReference.ConfidenceFilter))>  _
    Partial Public Class FilterBase
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="ConfidenceFilter", [Namespace]:="http://dev.virtualearth.net/webservices/v1/geocode")>  _
    Partial Public Class ConfidenceFilter
        Inherits GeocodeServiceReference.FilterBase
        
        Private MinimumConfidenceField As GeocodeServiceReference.Confidence
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property MinimumConfidence() As GeocodeServiceReference.Confidence
            Get
                Return Me.MinimumConfidenceField
            End Get
            Set
                If (Me.MinimumConfidenceField.Equals(value) <> true) Then
                    Me.MinimumConfidenceField = value
                    Me.RaisePropertyChanged("MinimumConfidence")
                End If
            End Set
        End Property
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="ResponseBase", [Namespace]:="http://dev.virtualearth.net/webservices/v1/common"),  _
     System.Runtime.Serialization.KnownTypeAttribute(GetType(GeocodeServiceReference.GeocodeResponse))>  _
    Partial Public Class ResponseBase
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private BrandLogoUriField As System.Uri
        
        Private ResponseSummaryField As GeocodeServiceReference.ResponseSummary
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property BrandLogoUri() As System.Uri
            Get
                Return Me.BrandLogoUriField
            End Get
            Set
                If (Object.ReferenceEquals(Me.BrandLogoUriField, value) <> true) Then
                    Me.BrandLogoUriField = value
                    Me.RaisePropertyChanged("BrandLogoUri")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property ResponseSummary() As GeocodeServiceReference.ResponseSummary
            Get
                Return Me.ResponseSummaryField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ResponseSummaryField, value) <> true) Then
                    Me.ResponseSummaryField = value
                    Me.RaisePropertyChanged("ResponseSummary")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="ResponseSummary", [Namespace]:="http://dev.virtualearth.net/webservices/v1/common")>  _
    Partial Public Class ResponseSummary
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private AuthenticationResultCodeField As GeocodeServiceReference.AuthenticationResultCode
        
        Private CopyrightField As String
        
        Private FaultReasonField As String
        
        Private StatusCodeField As GeocodeServiceReference.ResponseStatusCode
        
        Private TraceIdField As String
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property AuthenticationResultCode() As GeocodeServiceReference.AuthenticationResultCode
            Get
                Return Me.AuthenticationResultCodeField
            End Get
            Set
                If (Me.AuthenticationResultCodeField.Equals(value) <> true) Then
                    Me.AuthenticationResultCodeField = value
                    Me.RaisePropertyChanged("AuthenticationResultCode")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Copyright() As String
            Get
                Return Me.CopyrightField
            End Get
            Set
                If (Object.ReferenceEquals(Me.CopyrightField, value) <> true) Then
                    Me.CopyrightField = value
                    Me.RaisePropertyChanged("Copyright")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property FaultReason() As String
            Get
                Return Me.FaultReasonField
            End Get
            Set
                If (Object.ReferenceEquals(Me.FaultReasonField, value) <> true) Then
                    Me.FaultReasonField = value
                    Me.RaisePropertyChanged("FaultReason")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property StatusCode() As GeocodeServiceReference.ResponseStatusCode
            Get
                Return Me.StatusCodeField
            End Get
            Set
                If (Me.StatusCodeField.Equals(value) <> true) Then
                    Me.StatusCodeField = value
                    Me.RaisePropertyChanged("StatusCode")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property TraceId() As String
            Get
                Return Me.TraceIdField
            End Get
            Set
                If (Object.ReferenceEquals(Me.TraceIdField, value) <> true) Then
                    Me.TraceIdField = value
                    Me.RaisePropertyChanged("TraceId")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="GeocodeResponse", [Namespace]:="http://dev.virtualearth.net/webservices/v1/geocode")>  _
    Partial Public Class GeocodeResponse
        Inherits GeocodeServiceReference.ResponseBase
        
        Private ResultsField As System.Collections.ObjectModel.ObservableCollection(Of GeocodeServiceReference.GeocodeResult)
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Results() As System.Collections.ObjectModel.ObservableCollection(Of GeocodeServiceReference.GeocodeResult)
            Get
                Return Me.ResultsField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ResultsField, value) <> true) Then
                    Me.ResultsField = value
                    Me.RaisePropertyChanged("Results")
                End If
            End Set
        End Property
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="GeocodeResult", [Namespace]:="http://dev.virtualearth.net/webservices/v1/common"),  _
     System.Runtime.Serialization.KnownTypeAttribute(GetType(GeocodeServiceReference.GeocodeLocation)),  _
     System.Runtime.Serialization.KnownTypeAttribute(GetType(GeocodeServiceReference.UserLocation))>  _
    Partial Public Class GeocodeResult
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private AddressField As GeocodeServiceReference.Address
        
        Private BestViewField As Microsoft.Maps.MapControl.LocationRect
        
        Private ConfidenceField As GeocodeServiceReference.Confidence
        
        Private DisplayNameField As String
        
        Private EntityTypeField As String
        
        Private LocationsField As System.Collections.ObjectModel.ObservableCollection(Of GeocodeServiceReference.GeocodeLocation)
        
        Private MatchCodesField As System.Collections.ObjectModel.ObservableCollection(Of String)
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Address() As GeocodeServiceReference.Address
            Get
                Return Me.AddressField
            End Get
            Set
                If (Object.ReferenceEquals(Me.AddressField, value) <> true) Then
                    Me.AddressField = value
                    Me.RaisePropertyChanged("Address")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property BestView() As Microsoft.Maps.MapControl.LocationRect
            Get
                Return Me.BestViewField
            End Get
            Set
                If (Object.ReferenceEquals(Me.BestViewField, value) <> true) Then
                    Me.BestViewField = value
                    Me.RaisePropertyChanged("BestView")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Confidence() As GeocodeServiceReference.Confidence
            Get
                Return Me.ConfidenceField
            End Get
            Set
                If (Me.ConfidenceField.Equals(value) <> true) Then
                    Me.ConfidenceField = value
                    Me.RaisePropertyChanged("Confidence")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property DisplayName() As String
            Get
                Return Me.DisplayNameField
            End Get
            Set
                If (Object.ReferenceEquals(Me.DisplayNameField, value) <> true) Then
                    Me.DisplayNameField = value
                    Me.RaisePropertyChanged("DisplayName")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property EntityType() As String
            Get
                Return Me.EntityTypeField
            End Get
            Set
                If (Object.ReferenceEquals(Me.EntityTypeField, value) <> true) Then
                    Me.EntityTypeField = value
                    Me.RaisePropertyChanged("EntityType")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Locations() As System.Collections.ObjectModel.ObservableCollection(Of GeocodeServiceReference.GeocodeLocation)
            Get
                Return Me.LocationsField
            End Get
            Set
                If (Object.ReferenceEquals(Me.LocationsField, value) <> true) Then
                    Me.LocationsField = value
                    Me.RaisePropertyChanged("Locations")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property MatchCodes() As System.Collections.ObjectModel.ObservableCollection(Of String)
            Get
                Return Me.MatchCodesField
            End Get
            Set
                If (Object.ReferenceEquals(Me.MatchCodesField, value) <> true) Then
                    Me.MatchCodesField = value
                    Me.RaisePropertyChanged("MatchCodes")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="AuthenticationResultCode", [Namespace]:="http://dev.virtualearth.net/webservices/v1/common")>  _
    Public Enum AuthenticationResultCode As Integer
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        None = 0
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        NoCredentials = 1
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        ValidCredentials = 2
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        InvalidCredentials = 3
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        CredentialsExpired = 4
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        NotAuthorized = 7
    End Enum
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="ResponseStatusCode", [Namespace]:="http://dev.virtualearth.net/webservices/v1/common")>  _
    Public Enum ResponseStatusCode As Integer
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        Success = 0
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        BadRequest = 1
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        ServerError = 2
    End Enum
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute([Namespace]:="http://dev.virtualearth.net/webservices/v1/geocode/contracts", ConfigurationName:="GeocodeServiceReference.IGeocodeService")>  _
    Public Interface IGeocodeService
        
        <System.ServiceModel.OperationContractAttribute(AsyncPattern:=true, Action:="http://dev.virtualearth.net/webservices/v1/geocode/contracts/IGeocodeService/Geoc"& _ 
            "ode", ReplyAction:="http://dev.virtualearth.net/webservices/v1/geocode/contracts/IGeocodeService/Geoc"& _ 
            "odeResponse"),  _
         System.ServiceModel.FaultContractAttribute(GetType(GeocodeServiceReference.ResponseSummary), Action:="http://dev.virtualearth.net/webservices/v1/geocode/contracts/IGeocodeService/Geoc"& _ 
            "odeResponseSummaryFault", Name:="ResponseSummary", [Namespace]:="http://dev.virtualearth.net/webservices/v1/common")>  _
        Function BeginGeocode(ByVal request As GeocodeServiceReference.GeocodeRequest, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
        
        Function EndGeocode(ByVal result As System.IAsyncResult) As GeocodeServiceReference.GeocodeResponse
        
        <System.ServiceModel.OperationContractAttribute(AsyncPattern:=true, Action:="http://dev.virtualearth.net/webservices/v1/geocode/contracts/IGeocodeService/Reve"& _ 
            "rseGeocode", ReplyAction:="http://dev.virtualearth.net/webservices/v1/geocode/contracts/IGeocodeService/Reve"& _ 
            "rseGeocodeResponse"),  _
         System.ServiceModel.FaultContractAttribute(GetType(GeocodeServiceReference.ResponseSummary), Action:="http://dev.virtualearth.net/webservices/v1/geocode/contracts/IGeocodeService/Reve"& _ 
            "rseGeocodeResponseSummaryFault", Name:="ResponseSummary", [Namespace]:="http://dev.virtualearth.net/webservices/v1/common")>  _
        Function BeginReverseGeocode(ByVal request As GeocodeServiceReference.ReverseGeocodeRequest, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
        
        Function EndReverseGeocode(ByVal result As System.IAsyncResult) As GeocodeServiceReference.GeocodeResponse
    End Interface
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface IGeocodeServiceChannel
        Inherits GeocodeServiceReference.IGeocodeService, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class GeocodeCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Public Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        Public ReadOnly Property Result() As GeocodeServiceReference.GeocodeResponse
            Get
                MyBase.RaiseExceptionIfNecessary
                Return CType(Me.results(0),GeocodeServiceReference.GeocodeResponse)
            End Get
        End Property
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class ReverseGeocodeCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Public Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        Public ReadOnly Property Result() As GeocodeServiceReference.GeocodeResponse
            Get
                MyBase.RaiseExceptionIfNecessary
                Return CType(Me.results(0),GeocodeServiceReference.GeocodeResponse)
            End Get
        End Property
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class GeocodeServiceClient
        Inherits System.ServiceModel.ClientBase(Of GeocodeServiceReference.IGeocodeService)
        Implements GeocodeServiceReference.IGeocodeService
        
        Private onBeginGeocodeDelegate As BeginOperationDelegate
        
        Private onEndGeocodeDelegate As EndOperationDelegate
        
        Private onGeocodeCompletedDelegate As System.Threading.SendOrPostCallback
        
        Private onBeginReverseGeocodeDelegate As BeginOperationDelegate
        
        Private onEndReverseGeocodeDelegate As EndOperationDelegate
        
        Private onReverseGeocodeCompletedDelegate As System.Threading.SendOrPostCallback
        
        Private onBeginOpenDelegate As BeginOperationDelegate
        
        Private onEndOpenDelegate As EndOperationDelegate
        
        Private onOpenCompletedDelegate As System.Threading.SendOrPostCallback
        
        Private onBeginCloseDelegate As BeginOperationDelegate
        
        Private onEndCloseDelegate As EndOperationDelegate
        
        Private onCloseCompletedDelegate As System.Threading.SendOrPostCallback
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Property CookieContainer() As System.Net.CookieContainer
            Get
                Dim httpCookieContainerManager As System.ServiceModel.Channels.IHttpCookieContainerManager = Me.InnerChannel.GetProperty(Of System.ServiceModel.Channels.IHttpCookieContainerManager)
                If (Not (httpCookieContainerManager) Is Nothing) Then
                    Return httpCookieContainerManager.CookieContainer
                Else
                    Return Nothing
                End If
            End Get
            Set
                Dim httpCookieContainerManager As System.ServiceModel.Channels.IHttpCookieContainerManager = Me.InnerChannel.GetProperty(Of System.ServiceModel.Channels.IHttpCookieContainerManager)
                If (Not (httpCookieContainerManager) Is Nothing) Then
                    httpCookieContainerManager.CookieContainer = value
                Else
                    Throw New System.InvalidOperationException("Unable to set the CookieContainer. Please make sure the binding contains an HttpC"& _ 
                            "ookieContainerBindingElement.")
                End If
            End Set
        End Property
        
        Public Event GeocodeCompleted As System.EventHandler(Of GeocodeCompletedEventArgs)
        
        Public Event ReverseGeocodeCompleted As System.EventHandler(Of ReverseGeocodeCompletedEventArgs)
        
        Public Event OpenCompleted As System.EventHandler(Of System.ComponentModel.AsyncCompletedEventArgs)
        
        Public Event CloseCompleted As System.EventHandler(Of System.ComponentModel.AsyncCompletedEventArgs)
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function GeocodeServiceReference_IGeocodeService_BeginGeocode(ByVal request As GeocodeServiceReference.GeocodeRequest, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult Implements GeocodeServiceReference.IGeocodeService.BeginGeocode
            Return MyBase.Channel.BeginGeocode(request, callback, asyncState)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function GeocodeServiceReference_IGeocodeService_EndGeocode(ByVal result As System.IAsyncResult) As GeocodeServiceReference.GeocodeResponse Implements GeocodeServiceReference.IGeocodeService.EndGeocode
            Return MyBase.Channel.EndGeocode(result)
        End Function
        
        Private Function OnBeginGeocode(ByVal inValues() As Object, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Dim request As GeocodeServiceReference.GeocodeRequest = CType(inValues(0),GeocodeServiceReference.GeocodeRequest)
            Return CType(Me,GeocodeServiceReference.IGeocodeService).BeginGeocode(request, callback, asyncState)
        End Function
        
        Private Function OnEndGeocode(ByVal result As System.IAsyncResult) As Object()
            Dim retVal As GeocodeServiceReference.GeocodeResponse = CType(Me,GeocodeServiceReference.IGeocodeService).EndGeocode(result)
            Return New Object() {retVal}
        End Function
        
        Private Sub OnGeocodeCompleted(ByVal state As Object)
            If (Not (Me.GeocodeCompletedEvent) Is Nothing) Then
                Dim e As InvokeAsyncCompletedEventArgs = CType(state,InvokeAsyncCompletedEventArgs)
                RaiseEvent GeocodeCompleted(Me, New GeocodeCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState))
            End If
        End Sub
        
        Public Overloads Sub GeocodeAsync(ByVal request As GeocodeServiceReference.GeocodeRequest)
            Me.GeocodeAsync(request, Nothing)
        End Sub
        
        Public Overloads Sub GeocodeAsync(ByVal request As GeocodeServiceReference.GeocodeRequest, ByVal userState As Object)
            If (Me.onBeginGeocodeDelegate Is Nothing) Then
                Me.onBeginGeocodeDelegate = AddressOf Me.OnBeginGeocode
            End If
            If (Me.onEndGeocodeDelegate Is Nothing) Then
                Me.onEndGeocodeDelegate = AddressOf Me.OnEndGeocode
            End If
            If (Me.onGeocodeCompletedDelegate Is Nothing) Then
                Me.onGeocodeCompletedDelegate = AddressOf Me.OnGeocodeCompleted
            End If
            MyBase.InvokeAsync(Me.onBeginGeocodeDelegate, New Object() {request}, Me.onEndGeocodeDelegate, Me.onGeocodeCompletedDelegate, userState)
        End Sub
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function GeocodeServiceReference_IGeocodeService_BeginReverseGeocode(ByVal request As GeocodeServiceReference.ReverseGeocodeRequest, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult Implements GeocodeServiceReference.IGeocodeService.BeginReverseGeocode
            Return MyBase.Channel.BeginReverseGeocode(request, callback, asyncState)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function GeocodeServiceReference_IGeocodeService_EndReverseGeocode(ByVal result As System.IAsyncResult) As GeocodeServiceReference.GeocodeResponse Implements GeocodeServiceReference.IGeocodeService.EndReverseGeocode
            Return MyBase.Channel.EndReverseGeocode(result)
        End Function
        
        Private Function OnBeginReverseGeocode(ByVal inValues() As Object, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Dim request As GeocodeServiceReference.ReverseGeocodeRequest = CType(inValues(0),GeocodeServiceReference.ReverseGeocodeRequest)
            Return CType(Me,GeocodeServiceReference.IGeocodeService).BeginReverseGeocode(request, callback, asyncState)
        End Function
        
        Private Function OnEndReverseGeocode(ByVal result As System.IAsyncResult) As Object()
            Dim retVal As GeocodeServiceReference.GeocodeResponse = CType(Me,GeocodeServiceReference.IGeocodeService).EndReverseGeocode(result)
            Return New Object() {retVal}
        End Function
        
        Private Sub OnReverseGeocodeCompleted(ByVal state As Object)
            If (Not (Me.ReverseGeocodeCompletedEvent) Is Nothing) Then
                Dim e As InvokeAsyncCompletedEventArgs = CType(state,InvokeAsyncCompletedEventArgs)
                RaiseEvent ReverseGeocodeCompleted(Me, New ReverseGeocodeCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState))
            End If
        End Sub
        
        Public Overloads Sub ReverseGeocodeAsync(ByVal request As GeocodeServiceReference.ReverseGeocodeRequest)
            Me.ReverseGeocodeAsync(request, Nothing)
        End Sub
        
        Public Overloads Sub ReverseGeocodeAsync(ByVal request As GeocodeServiceReference.ReverseGeocodeRequest, ByVal userState As Object)
            If (Me.onBeginReverseGeocodeDelegate Is Nothing) Then
                Me.onBeginReverseGeocodeDelegate = AddressOf Me.OnBeginReverseGeocode
            End If
            If (Me.onEndReverseGeocodeDelegate Is Nothing) Then
                Me.onEndReverseGeocodeDelegate = AddressOf Me.OnEndReverseGeocode
            End If
            If (Me.onReverseGeocodeCompletedDelegate Is Nothing) Then
                Me.onReverseGeocodeCompletedDelegate = AddressOf Me.OnReverseGeocodeCompleted
            End If
            MyBase.InvokeAsync(Me.onBeginReverseGeocodeDelegate, New Object() {request}, Me.onEndReverseGeocodeDelegate, Me.onReverseGeocodeCompletedDelegate, userState)
        End Sub
        
        Private Function OnBeginOpen(ByVal inValues() As Object, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return CType(Me,System.ServiceModel.ICommunicationObject).BeginOpen(callback, asyncState)
        End Function
        
        Private Function OnEndOpen(ByVal result As System.IAsyncResult) As Object()
            CType(Me,System.ServiceModel.ICommunicationObject).EndOpen(result)
            Return Nothing
        End Function
        
        Private Sub OnOpenCompleted(ByVal state As Object)
            If (Not (Me.OpenCompletedEvent) Is Nothing) Then
                Dim e As InvokeAsyncCompletedEventArgs = CType(state,InvokeAsyncCompletedEventArgs)
                RaiseEvent OpenCompleted(Me, New System.ComponentModel.AsyncCompletedEventArgs(e.[Error], e.Cancelled, e.UserState))
            End If
        End Sub
        
        Public Overloads Sub OpenAsync()
            Me.OpenAsync(Nothing)
        End Sub
        
        Public Overloads Sub OpenAsync(ByVal userState As Object)
            If (Me.onBeginOpenDelegate Is Nothing) Then
                Me.onBeginOpenDelegate = AddressOf Me.OnBeginOpen
            End If
            If (Me.onEndOpenDelegate Is Nothing) Then
                Me.onEndOpenDelegate = AddressOf Me.OnEndOpen
            End If
            If (Me.onOpenCompletedDelegate Is Nothing) Then
                Me.onOpenCompletedDelegate = AddressOf Me.OnOpenCompleted
            End If
            MyBase.InvokeAsync(Me.onBeginOpenDelegate, Nothing, Me.onEndOpenDelegate, Me.onOpenCompletedDelegate, userState)
        End Sub
        
        Private Function OnBeginClose(ByVal inValues() As Object, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return CType(Me,System.ServiceModel.ICommunicationObject).BeginClose(callback, asyncState)
        End Function
        
        Private Function OnEndClose(ByVal result As System.IAsyncResult) As Object()
            CType(Me,System.ServiceModel.ICommunicationObject).EndClose(result)
            Return Nothing
        End Function
        
        Private Sub OnCloseCompleted(ByVal state As Object)
            If (Not (Me.CloseCompletedEvent) Is Nothing) Then
                Dim e As InvokeAsyncCompletedEventArgs = CType(state,InvokeAsyncCompletedEventArgs)
                RaiseEvent CloseCompleted(Me, New System.ComponentModel.AsyncCompletedEventArgs(e.[Error], e.Cancelled, e.UserState))
            End If
        End Sub
        
        Public Overloads Sub CloseAsync()
            Me.CloseAsync(Nothing)
        End Sub
        
        Public Overloads Sub CloseAsync(ByVal userState As Object)
            If (Me.onBeginCloseDelegate Is Nothing) Then
                Me.onBeginCloseDelegate = AddressOf Me.OnBeginClose
            End If
            If (Me.onEndCloseDelegate Is Nothing) Then
                Me.onEndCloseDelegate = AddressOf Me.OnEndClose
            End If
            If (Me.onCloseCompletedDelegate Is Nothing) Then
                Me.onCloseCompletedDelegate = AddressOf Me.OnCloseCompleted
            End If
            MyBase.InvokeAsync(Me.onBeginCloseDelegate, Nothing, Me.onEndCloseDelegate, Me.onCloseCompletedDelegate, userState)
        End Sub
        
        Protected Overrides Function CreateChannel() As GeocodeServiceReference.IGeocodeService
            Return New GeocodeServiceClientChannel(Me)
        End Function
        
        Private Class GeocodeServiceClientChannel
            Inherits ChannelBase(Of GeocodeServiceReference.IGeocodeService)
            Implements GeocodeServiceReference.IGeocodeService
            
            Public Sub New(ByVal client As System.ServiceModel.ClientBase(Of GeocodeServiceReference.IGeocodeService))
                MyBase.New(client)
            End Sub
            
            Public Function BeginGeocode(ByVal request As GeocodeServiceReference.GeocodeRequest, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult Implements GeocodeServiceReference.IGeocodeService.BeginGeocode
                Dim _args((1) - 1) As Object
                _args(0) = request
                Dim _result As System.IAsyncResult = MyBase.BeginInvoke("Geocode", _args, callback, asyncState)
                Return _result
            End Function
            
            Public Function EndGeocode(ByVal result As System.IAsyncResult) As GeocodeServiceReference.GeocodeResponse Implements GeocodeServiceReference.IGeocodeService.EndGeocode
                Dim _args((0) - 1) As Object
                Dim _result As GeocodeServiceReference.GeocodeResponse = CType(MyBase.EndInvoke("Geocode", _args, result),GeocodeServiceReference.GeocodeResponse)
                Return _result
            End Function
            
            Public Function BeginReverseGeocode(ByVal request As GeocodeServiceReference.ReverseGeocodeRequest, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult Implements GeocodeServiceReference.IGeocodeService.BeginReverseGeocode
                Dim _args((1) - 1) As Object
                _args(0) = request
                Dim _result As System.IAsyncResult = MyBase.BeginInvoke("ReverseGeocode", _args, callback, asyncState)
                Return _result
            End Function
            
            Public Function EndReverseGeocode(ByVal result As System.IAsyncResult) As GeocodeServiceReference.GeocodeResponse Implements GeocodeServiceReference.IGeocodeService.EndReverseGeocode
                Dim _args((0) - 1) As Object
                Dim _result As GeocodeServiceReference.GeocodeResponse = CType(MyBase.EndInvoke("ReverseGeocode", _args, result),GeocodeServiceReference.GeocodeResponse)
                Return _result
            End Function
        End Class
    End Class
End Namespace
