'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.4927
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On


'Original file name:
'Generation date: 12/22/2009 1:34:21 PM
Namespace SamplesService
    '''<summary>
    '''There are no comments for SampleProjects in the schema.
    '''</summary>
    Partial Public Class SampleProjects
        Inherits Global.System.Data.Services.Client.DataServiceContext
        '''<summary>
        '''Initialize a new SampleProjects object.
        '''</summary>
        Public Sub New(ByVal serviceRoot As Global.System.Uri)
            MyBase.New(serviceRoot)
            Me.ResolveName = AddressOf Me.ResolveNameFromType
            Me.ResolveType = AddressOf Me.ResolveTypeFromName
            Me.OnContextCreated
        End Sub
        Partial Private Sub OnContextCreated()
        End Sub
        Private Shared ROOTNAMESPACE As String = GetType(SamplesService.SampleProjects).Namespace.Remove(GetType(SamplesService.SampleProjects).Namespace.LastIndexOf("SamplesService"))
        '''<summary>
        '''Since the namespace configured for this service reference
        '''in Visual Studio is different from the one indicated in the
        '''server schema, use type-mappers to map between the two.
        '''</summary>
        Protected Function ResolveTypeFromName(ByVal typeName As String) As Global.System.Type
            If typeName.StartsWith("VBADONETDataService", Global.System.StringComparison.OrdinalIgnoreCase) Then
                Return Me.GetType.Assembly.GetType(String.Concat(String.Concat(ROOTNAMESPACE, "SamplesService"), typeName.Substring(19)), true)
            End If
            Return Nothing
        End Function
        '''<summary>
        '''Since the namespace configured for this service reference
        '''in Visual Studio is different from the one indicated in the
        '''server schema, use type-mappers to map between the two.
        '''</summary>
        Protected Function ResolveNameFromType(ByVal clientType As Global.System.Type) As String
            If clientType.Namespace.Equals(String.Concat(ROOTNAMESPACE, "SamplesService"), Global.System.StringComparison.OrdinalIgnoreCase) Then
                Return String.Concat("VBADONETDataService.", clientType.Name)
            End If
            Return Nothing
        End Function
        '''<summary>
        '''There are no comments for Projects in the schema.
        '''</summary>
        Public ReadOnly Property Projects() As Global.System.Data.Services.Client.DataServiceQuery(Of Project)
            Get
                If (Me._Projects Is Nothing) Then
                    Me._Projects = MyBase.CreateQuery(Of Project)("Projects")
                End If
                Return Me._Projects
            End Get
        End Property
        Private _Projects As Global.System.Data.Services.Client.DataServiceQuery(Of Project)
        '''<summary>
        '''There are no comments for Categories in the schema.
        '''</summary>
        Public ReadOnly Property Categories() As Global.System.Data.Services.Client.DataServiceQuery(Of Category)
            Get
                If (Me._Categories Is Nothing) Then
                    Me._Categories = MyBase.CreateQuery(Of Category)("Categories")
                End If
                Return Me._Categories
            End Get
        End Property
        Private _Categories As Global.System.Data.Services.Client.DataServiceQuery(Of Category)
        '''<summary>
        '''There are no comments for Projects in the schema.
        '''</summary>
        Public Sub AddToProjects(ByVal project As Project)
            MyBase.AddObject("Projects", project)
        End Sub
        '''<summary>
        '''There are no comments for Categories in the schema.
        '''</summary>
        Public Sub AddToCategories(ByVal category As Category)
            MyBase.AddObject("Categories", category)
        End Sub
    End Class
    '''<summary>
    '''There are no comments for VBADONETDataService.Project in the schema.
    '''</summary>
    '''<KeyProperties>
    '''ProjectName
    '''</KeyProperties>
    <Global.System.Data.Services.Common.DataServiceKeyAttribute("ProjectName")>  _
    Partial Public Class Project
        '''<summary>
        '''Create a new Project object.
        '''</summary>
        '''<param name="projectName">Initial value of ProjectName.</param>
        Public Shared Function CreateProject(ByVal projectName As String) As Project
            Dim project As Project = New Project
            project.ProjectName = projectName
            Return project
        End Function
        '''<summary>
        '''There are no comments for Property ProjectName in the schema.
        '''</summary>
        Public Property ProjectName() As String
            Get
                Return Me._ProjectName
            End Get
            Set
                Me.OnProjectNameChanging(value)
                Me._ProjectName = value
                Me.OnProjectNameChanged
            End Set
        End Property
        Private _ProjectName As String
        Partial Private Sub OnProjectNameChanging(ByVal value As String)
        End Sub
        Partial Private Sub OnProjectNameChanged()
        End Sub
        '''<summary>
        '''There are no comments for Property Owner in the schema.
        '''</summary>
        Public Property Owner() As String
            Get
                Return Me._Owner
            End Get
            Set
                Me.OnOwnerChanging(value)
                Me._Owner = value
                Me.OnOwnerChanged
            End Set
        End Property
        Private _Owner As String
        Partial Private Sub OnOwnerChanging(ByVal value As String)
        End Sub
        Partial Private Sub OnOwnerChanged()
        End Sub
        '''<summary>
        '''There are no comments for ProjectCategory in the schema.
        '''</summary>
        Public Property ProjectCategory() As Category
            Get
                Return Me._ProjectCategory
            End Get
            Set
                Me._ProjectCategory = value
            End Set
        End Property
        Private _ProjectCategory As Category
    End Class
    '''<summary>
    '''There are no comments for VBADONETDataService.Category in the schema.
    '''</summary>
    '''<KeyProperties>
    '''CategoryName
    '''</KeyProperties>
    <Global.System.Data.Services.Common.DataServiceKeyAttribute("CategoryName")>  _
    Partial Public Class Category
        '''<summary>
        '''Create a new Category object.
        '''</summary>
        '''<param name="categoryName">Initial value of CategoryName.</param>
        Public Shared Function CreateCategory(ByVal categoryName As String) As Category
            Dim category As Category = New Category
            category.CategoryName = categoryName
            Return category
        End Function
        '''<summary>
        '''There are no comments for Property CategoryName in the schema.
        '''</summary>
        Public Property CategoryName() As String
            Get
                Return Me._CategoryName
            End Get
            Set
                Me.OnCategoryNameChanging(value)
                Me._CategoryName = value
                Me.OnCategoryNameChanged
            End Set
        End Property
        Private _CategoryName As String
        Partial Private Sub OnCategoryNameChanging(ByVal value As String)
        End Sub
        Partial Private Sub OnCategoryNameChanged()
        End Sub
    End Class
End Namespace
