'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.1433
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System
Imports System.Runtime.Serialization

Namespace Microsoft.ServiceModel.Samples
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="Person", [Namespace]:="http://schemas.datacontract.org/2004/07/Microsoft.ServiceModel.Samples", IsReference:=true),  _
     System.SerializableAttribute()>  _
    Partial Public Class Person
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private AgeField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private FriendsField() As Microsoft.ServiceModel.Samples.Person
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private GenderField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private LocationField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private NameField As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Age() As Integer
            Get
                Return Me.AgeField
            End Get
            Set
                If (Me.AgeField.Equals(value) <> true) Then
                    Me.AgeField = value
                    Me.RaisePropertyChanged("Age")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Friends() As Microsoft.ServiceModel.Samples.Person()
            Get
                Return Me.FriendsField
            End Get
            Set
                If (Object.ReferenceEquals(Me.FriendsField, value) <> true) Then
                    Me.FriendsField = value
                    Me.RaisePropertyChanged("Friends")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Gender() As String
            Get
                Return Me.GenderField
            End Get
            Set
                If (Object.ReferenceEquals(Me.GenderField, value) <> true) Then
                    Me.GenderField = value
                    Me.RaisePropertyChanged("Gender")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Location() As String
            Get
                Return Me.LocationField
            End Get
            Set
                If (Object.ReferenceEquals(Me.LocationField, value) <> true) Then
                    Me.LocationField = value
                    Me.RaisePropertyChanged("Location")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Name() As String
            Get
                Return Me.NameField
            End Get
            Set
                If (Object.ReferenceEquals(Me.NameField, value) <> true) Then
                    Me.NameField = value
                    Me.RaisePropertyChanged("Name")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute([Namespace]:="http://Microsoft.ServiceModel.Samples", ConfigurationName:="Microsoft.ServiceModel.Samples.ISocialNetwork")>  _
    Public Interface ISocialNetwork
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://Microsoft.ServiceModel.Samples/ISocialNetwork/GetPeopleInNetwork", ReplyAction:="http://Microsoft.ServiceModel.Samples/ISocialNetwork/GetPeopleInNetworkResponse")>  _
        Function GetPeopleInNetwork(ByVal p As Microsoft.ServiceModel.Samples.Person) As Microsoft.ServiceModel.Samples.Person()
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://Microsoft.ServiceModel.Samples/ISocialNetwork/GetMutualFriends", ReplyAction:="http://Microsoft.ServiceModel.Samples/ISocialNetwork/GetMutualFriendsResponse")>  _
        Function GetMutualFriends(ByVal p As Microsoft.ServiceModel.Samples.Person) As Microsoft.ServiceModel.Samples.Person()
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://Microsoft.ServiceModel.Samples/ISocialNetwork/GetCommonFriends", ReplyAction:="http://Microsoft.ServiceModel.Samples/ISocialNetwork/GetCommonFriendsResponse")>  _
        Function GetCommonFriends(ByVal p() As Microsoft.ServiceModel.Samples.Person) As Microsoft.ServiceModel.Samples.Person()
    End Interface
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")>  _
    Public Interface ISocialNetworkChannel
        Inherits Microsoft.ServiceModel.Samples.ISocialNetwork, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")>  _
    Partial Public Class SocialNetworkClient
        Inherits System.ServiceModel.ClientBase(Of Microsoft.ServiceModel.Samples.ISocialNetwork)
        Implements Microsoft.ServiceModel.Samples.ISocialNetwork
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Function GetPeopleInNetwork(ByVal p As Microsoft.ServiceModel.Samples.Person) As Microsoft.ServiceModel.Samples.Person() Implements Microsoft.ServiceModel.Samples.ISocialNetwork.GetPeopleInNetwork
            Return MyBase.Channel.GetPeopleInNetwork(p)
        End Function
        
        Public Function GetMutualFriends(ByVal p As Microsoft.ServiceModel.Samples.Person) As Microsoft.ServiceModel.Samples.Person() Implements Microsoft.ServiceModel.Samples.ISocialNetwork.GetMutualFriends
            Return MyBase.Channel.GetMutualFriends(p)
        End Function
        
        Public Function GetCommonFriends(ByVal p() As Microsoft.ServiceModel.Samples.Person) As Microsoft.ServiceModel.Samples.Person() Implements Microsoft.ServiceModel.Samples.ISocialNetwork.GetCommonFriends
            Return MyBase.Channel.GetCommonFriends(p)
        End Function
    End Class
End Namespace
