'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.42
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

<Assembly: System.Runtime.Serialization.ContractNamespaceAttribute("urn:uddi-org:api_v2", ClrNamespace:="uddiorg.api_v2")> 


<System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0"), _
 System.ServiceModel.ServiceContractAttribute([Namespace]:="urn:uddi-org:inquiry_v2", ConfigurationName:="Inquire")> _
Public Interface Inquire

    <System.ServiceModel.OperationContractAttribute(Action:="find_binding", ReplyAction:="*"), _
     System.ServiceModel.FaultContractAttribute(GetType(uddiorg.api_v2.dispositionReport), Action:="find_binding", name:="dispositionReport", [Namespace]:="urn:uddi-org:api_v2"), _
     System.ServiceModel.XmlSerializerFormatAttribute()> _
    Function find_binding(ByVal request As find_bindingRequest) As find_bindingResponse

    <System.ServiceModel.OperationContractAttribute(Action:="find_business", ReplyAction:="*"), _
     System.ServiceModel.FaultContractAttribute(GetType(uddiorg.api_v2.dispositionReport), Action:="find_business", name:="dispositionReport", [Namespace]:="urn:uddi-org:api_v2"), _
     System.ServiceModel.XmlSerializerFormatAttribute()> _
    Function find_business(ByVal request As find_businessRequest) As find_businessResponse

    <System.ServiceModel.OperationContractAttribute(Action:="find_relatedBusinesses", ReplyAction:="*"), _
     System.ServiceModel.FaultContractAttribute(GetType(uddiorg.api_v2.dispositionReport), Action:="find_relatedBusinesses", name:="dispositionReport", [Namespace]:="urn:uddi-org:api_v2"), _
     System.ServiceModel.XmlSerializerFormatAttribute()> _
    Function find_relatedBusinesses(ByVal request As find_relatedBusinessesRequest) As find_relatedBusinessesResponse

    <System.ServiceModel.OperationContractAttribute(Action:="find_service", ReplyAction:="*"), _
     System.ServiceModel.FaultContractAttribute(GetType(uddiorg.api_v2.dispositionReport), Action:="find_service", name:="dispositionReport", [Namespace]:="urn:uddi-org:api_v2"), _
     System.ServiceModel.XmlSerializerFormatAttribute()> _
    Function find_service(ByVal request As find_serviceRequest) As find_serviceResponse

    <System.ServiceModel.OperationContractAttribute(Action:="find_tModel", ReplyAction:="*"), _
     System.ServiceModel.FaultContractAttribute(GetType(uddiorg.api_v2.dispositionReport), Action:="find_tModel", name:="dispositionReport", [Namespace]:="urn:uddi-org:api_v2"), _
     System.ServiceModel.XmlSerializerFormatAttribute()> _
    Function find_tModel(ByVal request As find_tModelRequest) As find_tModelResponse

    <System.ServiceModel.OperationContractAttribute(Action:="get_bindingDetail", ReplyAction:="*"), _
     System.ServiceModel.FaultContractAttribute(GetType(uddiorg.api_v2.dispositionReport), Action:="get_bindingDetail", name:="dispositionReport", [Namespace]:="urn:uddi-org:api_v2"), _
     System.ServiceModel.XmlSerializerFormatAttribute()> _
    Function get_bindingDetail(ByVal request As get_bindingDetailRequest) As find_bindingResponse

    <System.ServiceModel.OperationContractAttribute(Action:="get_businessDetail", ReplyAction:="*"), _
     System.ServiceModel.FaultContractAttribute(GetType(uddiorg.api_v2.dispositionReport), Action:="get_businessDetail", name:="dispositionReport", [Namespace]:="urn:uddi-org:api_v2"), _
     System.ServiceModel.XmlSerializerFormatAttribute()> _
    Function get_businessDetail(ByVal request As get_businessDetailRequest) As get_businessDetailResponse

    <System.ServiceModel.OperationContractAttribute(Action:="get_businessDetailExt", ReplyAction:="*"), _
     System.ServiceModel.FaultContractAttribute(GetType(uddiorg.api_v2.dispositionReport), Action:="get_businessDetailExt", name:="dispositionReport", [Namespace]:="urn:uddi-org:api_v2"), _
     System.ServiceModel.XmlSerializerFormatAttribute()> _
    Function get_businessDetailExt(ByVal request As get_businessDetailExtRequest) As get_businessDetailExtResponse

    <System.ServiceModel.OperationContractAttribute(Action:="get_serviceDetail", ReplyAction:="*"), _
     System.ServiceModel.FaultContractAttribute(GetType(uddiorg.api_v2.dispositionReport), Action:="get_serviceDetail", name:="dispositionReport", [Namespace]:="urn:uddi-org:api_v2"), _
     System.ServiceModel.XmlSerializerFormatAttribute()> _
    Function get_serviceDetail(ByVal request As get_serviceDetailRequest) As get_serviceDetailResponse

    <System.ServiceModel.OperationContractAttribute(Action:="get_tModelDetail", ReplyAction:="*"), _
     System.ServiceModel.FaultContractAttribute(GetType(uddiorg.api_v2.dispositionReport), Action:="get_tModelDetail", name:="dispositionReport", [Namespace]:="urn:uddi-org:api_v2"), _
     System.ServiceModel.XmlSerializerFormatAttribute()> _
    Function get_tModelDetail(ByVal request As get_tModelDetailRequest) As get_tModelDetailResponse
End Interface

<System.Diagnostics.DebuggerStepThroughAttribute(), _
 System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0"), _
 System.ServiceModel.MessageContractAttribute(IsWrapped:=False)> _
Partial Public Class find_bindingRequest

    <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="urn:uddi-org:api_v2", Order:=0)> _
    Public find_binding As find_binding

    Public Sub New()
        MyBase.New()
    End Sub

    Public Sub New(ByVal find_binding As find_binding)
        MyBase.New()
        Me.find_binding = find_binding
    End Sub
End Class

<System.Diagnostics.DebuggerStepThroughAttribute(), _
 System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0"), _
 System.ServiceModel.MessageContractAttribute(IsWrapped:=False)> _
Partial Public Class find_bindingResponse

    <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="urn:uddi-org:api_v2", Order:=0)> _
    Public bindingDetail As bindingDetail

    Public Sub New()
        MyBase.New()
    End Sub

    Public Sub New(ByVal bindingDetail As bindingDetail)
        MyBase.New()
        Me.bindingDetail = bindingDetail
    End Sub
End Class

<System.Diagnostics.DebuggerStepThroughAttribute(), _
 System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0"), _
 System.ServiceModel.MessageContractAttribute(IsWrapped:=False)> _
Partial Public Class find_businessRequest

    <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="urn:uddi-org:api_v2", Order:=0)> _
    Public find_business As find_business

    Public Sub New()
        MyBase.New()
    End Sub

    Public Sub New(ByVal find_business As find_business)
        MyBase.New()
        Me.find_business = find_business
    End Sub
End Class

<System.Diagnostics.DebuggerStepThroughAttribute(), _
 System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0"), _
 System.ServiceModel.MessageContractAttribute(IsWrapped:=False)> _
Partial Public Class find_businessResponse

    <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="urn:uddi-org:api_v2", Order:=0)> _
    Public businessList As businessList

    Public Sub New()
        MyBase.New()
    End Sub

    Public Sub New(ByVal businessList As businessList)
        MyBase.New()
        Me.businessList = businessList
    End Sub
End Class

<System.Diagnostics.DebuggerStepThroughAttribute(), _
 System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0"), _
 System.ServiceModel.MessageContractAttribute(IsWrapped:=False)> _
Partial Public Class find_relatedBusinessesRequest

    <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="urn:uddi-org:api_v2", Order:=0)> _
    Public find_relatedBusinesses As find_relatedBusinesses

    Public Sub New()
        MyBase.New()
    End Sub

    Public Sub New(ByVal find_relatedBusinesses As find_relatedBusinesses)
        MyBase.New()
        Me.find_relatedBusinesses = find_relatedBusinesses
    End Sub
End Class

<System.Diagnostics.DebuggerStepThroughAttribute(), _
 System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0"), _
 System.ServiceModel.MessageContractAttribute(IsWrapped:=False)> _
Partial Public Class find_relatedBusinessesResponse

    <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="urn:uddi-org:api_v2", Order:=0)> _
    Public relatedBusinessesList As relatedBusinessesList

    Public Sub New()
        MyBase.New()
    End Sub

    Public Sub New(ByVal relatedBusinessesList As relatedBusinessesList)
        MyBase.New()
        Me.relatedBusinessesList = relatedBusinessesList
    End Sub
End Class

<System.Diagnostics.DebuggerStepThroughAttribute(), _
 System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0"), _
 System.ServiceModel.MessageContractAttribute(IsWrapped:=False)> _
Partial Public Class find_serviceRequest

    <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="urn:uddi-org:api_v2", Order:=0)> _
    Public find_service As find_service

    Public Sub New()
        MyBase.New()
    End Sub

    Public Sub New(ByVal find_service As find_service)
        MyBase.New()
        Me.find_service = find_service
    End Sub
End Class

<System.Diagnostics.DebuggerStepThroughAttribute(), _
 System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0"), _
 System.ServiceModel.MessageContractAttribute(IsWrapped:=False)> _
Partial Public Class find_serviceResponse

    <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="urn:uddi-org:api_v2", Order:=0)> _
    Public serviceList As serviceList

    Public Sub New()
        MyBase.New()
    End Sub

    Public Sub New(ByVal serviceList As serviceList)
        MyBase.New()
        Me.serviceList = serviceList
    End Sub
End Class

<System.Diagnostics.DebuggerStepThroughAttribute(), _
 System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0"), _
 System.ServiceModel.MessageContractAttribute(IsWrapped:=False)> _
Partial Public Class find_tModelRequest

    <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="urn:uddi-org:api_v2", Order:=0)> _
    Public find_tModel As find_tModel

    Public Sub New()
        MyBase.New()
    End Sub

    Public Sub New(ByVal find_tModel As find_tModel)
        MyBase.New()
        Me.find_tModel = find_tModel
    End Sub
End Class

<System.Diagnostics.DebuggerStepThroughAttribute(), _
 System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0"), _
 System.ServiceModel.MessageContractAttribute(IsWrapped:=False)> _
Partial Public Class find_tModelResponse

    <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="urn:uddi-org:api_v2", Order:=0)> _
    Public tModelList As tModelList

    Public Sub New()
        MyBase.New()
    End Sub

    Public Sub New(ByVal tModelList As tModelList)
        MyBase.New()
        Me.tModelList = tModelList
    End Sub
End Class

<System.Diagnostics.DebuggerStepThroughAttribute(), _
 System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0"), _
 System.ServiceModel.MessageContractAttribute(IsWrapped:=False)> _
Partial Public Class get_bindingDetailRequest

    <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="urn:uddi-org:api_v2", Order:=0)> _
    Public get_bindingDetail As get_bindingDetail

    Public Sub New()
        MyBase.New()
    End Sub

    Public Sub New(ByVal get_bindingDetail As get_bindingDetail)
        MyBase.New()
        Me.get_bindingDetail = get_bindingDetail
    End Sub
End Class

<System.Diagnostics.DebuggerStepThroughAttribute(), _
 System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0"), _
 System.ServiceModel.MessageContractAttribute(IsWrapped:=False)> _
Partial Public Class get_businessDetailRequest

    <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="urn:uddi-org:api_v2", Order:=0)> _
    Public get_businessDetail As get_businessDetail

    Public Sub New()
        MyBase.New()
    End Sub

    Public Sub New(ByVal get_businessDetail As get_businessDetail)
        MyBase.New()
        Me.get_businessDetail = get_businessDetail
    End Sub
End Class

<System.Diagnostics.DebuggerStepThroughAttribute(), _
 System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0"), _
 System.ServiceModel.MessageContractAttribute(IsWrapped:=False)> _
Partial Public Class get_businessDetailResponse

    <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="urn:uddi-org:api_v2", Order:=0)> _
    Public businessDetail As businessDetail

    Public Sub New()
        MyBase.New()
    End Sub

    Public Sub New(ByVal businessDetail As businessDetail)
        MyBase.New()
        Me.businessDetail = businessDetail
    End Sub
End Class

<System.Diagnostics.DebuggerStepThroughAttribute(), _
 System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0"), _
 System.ServiceModel.MessageContractAttribute(IsWrapped:=False)> _
Partial Public Class get_businessDetailExtRequest

    <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="urn:uddi-org:api_v2", Order:=0)> _
    Public get_businessDetailExt As get_businessDetailExt

    Public Sub New()
        MyBase.New()
    End Sub

    Public Sub New(ByVal get_businessDetailExt As get_businessDetailExt)
        MyBase.New()
        Me.get_businessDetailExt = get_businessDetailExt
    End Sub
End Class

<System.Diagnostics.DebuggerStepThroughAttribute(), _
 System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0"), _
 System.ServiceModel.MessageContractAttribute(IsWrapped:=False)> _
Partial Public Class get_businessDetailExtResponse

    <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="urn:uddi-org:api_v2", Order:=0)> _
    Public businessDetailExt As businessDetailExt

    Public Sub New()
        MyBase.New()
    End Sub

    Public Sub New(ByVal businessDetailExt As businessDetailExt)
        MyBase.New()
        Me.businessDetailExt = businessDetailExt
    End Sub
End Class

<System.Diagnostics.DebuggerStepThroughAttribute(), _
 System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0"), _
 System.ServiceModel.MessageContractAttribute(IsWrapped:=False)> _
Partial Public Class get_serviceDetailRequest

    <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="urn:uddi-org:api_v2", Order:=0)> _
    Public get_serviceDetail As get_serviceDetail

    Public Sub New()
        MyBase.New()
    End Sub

    Public Sub New(ByVal get_serviceDetail As get_serviceDetail)
        MyBase.New()
        Me.get_serviceDetail = get_serviceDetail
    End Sub
End Class

<System.Diagnostics.DebuggerStepThroughAttribute(), _
 System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0"), _
 System.ServiceModel.MessageContractAttribute(IsWrapped:=False)> _
Partial Public Class get_serviceDetailResponse

    <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="urn:uddi-org:api_v2", Order:=0)> _
    Public serviceDetail As serviceDetail

    Public Sub New()
        MyBase.New()
    End Sub

    Public Sub New(ByVal serviceDetail As serviceDetail)
        MyBase.New()
        Me.serviceDetail = serviceDetail
    End Sub
End Class

<System.Diagnostics.DebuggerStepThroughAttribute(), _
 System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0"), _
 System.ServiceModel.MessageContractAttribute(IsWrapped:=False)> _
Partial Public Class get_tModelDetailRequest

    <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="urn:uddi-org:api_v2", Order:=0)> _
    Public get_tModelDetail As get_tModelDetail

    Public Sub New()
        MyBase.New()
    End Sub

    Public Sub New(ByVal get_tModelDetail As get_tModelDetail)
        MyBase.New()
        Me.get_tModelDetail = get_tModelDetail
    End Sub
End Class

<System.Diagnostics.DebuggerStepThroughAttribute(), _
 System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0"), _
 System.ServiceModel.MessageContractAttribute(IsWrapped:=False)> _
Partial Public Class get_tModelDetailResponse

    <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="urn:uddi-org:api_v2", Order:=0)> _
    Public tModelDetail As tModelDetail

    Public Sub New()
        MyBase.New()
    End Sub

    Public Sub New(ByVal tModelDetail As tModelDetail)
        MyBase.New()
        Me.tModelDetail = tModelDetail
    End Sub
End Class

<System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")> _
Public Interface InquireChannel
    Inherits Inquire, System.ServiceModel.IClientChannel
End Interface

<System.Diagnostics.DebuggerStepThroughAttribute(), _
 System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")> _
Partial Public Class InquireClient
    Inherits System.ServiceModel.ClientBase(Of Inquire)
    Implements Inquire

    Public Sub New()
        MyBase.New()
    End Sub

    Public Sub New(ByVal endpointConfigurationName As String)
        MyBase.New(endpointConfigurationName)
    End Sub

    Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
        MyBase.New(endpointConfigurationName, remoteAddress)
    End Sub

    Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
        MyBase.New(endpointConfigurationName, remoteAddress)
    End Sub

    Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
        MyBase.New(binding, remoteAddress)
    End Sub

    Public Function find_binding(ByVal request As find_bindingRequest) As find_bindingResponse Implements Inquire.find_binding
        Return MyBase.Channel.find_binding(request)
    End Function

    Public Function find_business(ByVal request As find_businessRequest) As find_businessResponse Implements Inquire.find_business
        Return MyBase.Channel.find_business(request)
    End Function

    Public Function find_relatedBusinesses(ByVal request As find_relatedBusinessesRequest) As find_relatedBusinessesResponse Implements Inquire.find_relatedBusinesses
        Return MyBase.Channel.find_relatedBusinesses(request)
    End Function

    Public Function find_service(ByVal request As find_serviceRequest) As find_serviceResponse Implements Inquire.find_service
        Return MyBase.Channel.find_service(request)
    End Function

    Public Function find_tModel(ByVal request As find_tModelRequest) As find_tModelResponse Implements Inquire.find_tModel
        Return MyBase.Channel.find_tModel(request)
    End Function

    Public Function get_bindingDetail(ByVal request As get_bindingDetailRequest) As find_bindingResponse Implements Inquire.get_bindingDetail
        Return MyBase.Channel.get_bindingDetail(request)
    End Function

    Public Function get_businessDetail(ByVal request As get_businessDetailRequest) As get_businessDetailResponse Implements Inquire.get_businessDetail
        Return MyBase.Channel.get_businessDetail(request)
    End Function

    Public Function get_businessDetailExt(ByVal request As get_businessDetailExtRequest) As get_businessDetailExtResponse Implements Inquire.get_businessDetailExt
        Return MyBase.Channel.get_businessDetailExt(request)
    End Function

    Public Function get_serviceDetail(ByVal request As get_serviceDetailRequest) As get_serviceDetailResponse Implements Inquire.get_serviceDetail
        Return MyBase.Channel.get_serviceDetail(request)
    End Function

    Public Function get_tModelDetail(ByVal request As get_tModelDetailRequest) As get_tModelDetailResponse Implements Inquire.get_tModelDetail
        Return MyBase.Channel.get_tModelDetail(request)
    End Function
End Class

Namespace uddiorg.api_v2

    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0"), _
     System.Xml.Serialization.XmlSchemaProviderAttribute("ExportSchema"), _
     System.Xml.Serialization.XmlRootAttribute(IsNullable:=False)> _
    Partial Public Class dispositionReport
        Inherits Object
        Implements System.Xml.Serialization.IXmlSerializable

        Private nodesField() As System.Xml.XmlNode

        Private Shared typeName As System.Xml.XmlQualifiedName = New System.Xml.XmlQualifiedName("dispositionReport", "urn:uddi-org:api_v2")

        Public Property Nodes() As System.Xml.XmlNode()
            Get
                Return Me.nodesField
            End Get
            Set(ByVal value As System.Xml.XmlNode())
                Me.nodesField = value
            End Set
        End Property

        Public Sub ReadXml(ByVal reader As System.Xml.XmlReader) Implements System.Xml.Serialization.IXmlSerializable.ReadXml
            Me.nodesField = System.Runtime.Serialization.XmlSerializableServices.ReadNodes(reader)
        End Sub

        Public Sub WriteXml(ByVal writer As System.Xml.XmlWriter) Implements System.Xml.Serialization.IXmlSerializable.WriteXml
            System.Runtime.Serialization.XmlSerializableServices.WriteNodes(writer, Me.Nodes)
        End Sub

        Public Function GetSchema() As System.Xml.Schema.XmlSchema Implements System.Xml.Serialization.IXmlSerializable.GetSchema
            Return Nothing
        End Function

        Public Shared Function ExportSchema(ByVal schemas As System.Xml.Schema.XmlSchemaSet) As System.Xml.XmlQualifiedName
            System.Runtime.Serialization.XmlSerializableServices.AddDefaultSchema(schemas, typeName)
            Return typeName
        End Function
    End Class
End Namespace
