#!/bin/sh
# ==++==
# 
#   Copyright (c) Microsoft Corporation.  All rights reserved.
# 
# ==--==

if test X"$1" = X"veron"
then
ACTION="-m -cg 1.1. Everything"
fi

if test X"$1" = X"veroff"
then
ACTION="-m -cg 1.1. FullTrust"
fi

echo "yes" | clix ${_NTTREE}/caspol.exe ${ACTION}


