'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.3603
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

<Assembly: Global.System.Data.Objects.DataClasses.EdmSchemaAttribute("e5ff41a6-d93b-44db-a501-cbd1571c3677")> 
Namespace VBEFEntityDataModel.TablePerHierarchy
    'Original file name:
    'Generation date: 2009/10/27 15:47:28
    '''<summary>
    '''There are no comments for EFTPHEntities in the schema.
    '''</summary>
    Partial Public Class EFTPHEntities
        Inherits Global.System.Data.Objects.ObjectContext
        '''<summary>
        '''Initializes a new EFTPHEntities object using the connection string found in the 'EFTPHEntities' section of the application configuration file.
        '''</summary>
        Public Sub New()
            MyBase.New("name=EFTPHEntities", "EFTPHEntities")
            Me.OnContextCreated()
        End Sub
        '''<summary>
        '''Initialize a new EFTPHEntities object.
        '''</summary>
        Public Sub New(ByVal connectionString As String)
            MyBase.New(connectionString, "EFTPHEntities")
            Me.OnContextCreated()
        End Sub
        '''<summary>
        '''Initialize a new EFTPHEntities object.
        '''</summary>
        Public Sub New(ByVal connection As Global.System.Data.EntityClient.EntityConnection)
            MyBase.New(connection, "EFTPHEntities")
            Me.OnContextCreated()
        End Sub
        Partial Private Sub OnContextCreated()
        End Sub
        '''<summary>
        '''There are no comments for PersonSet in the schema.
        '''</summary>
        Public ReadOnly Property PersonSet() As Global.System.Data.Objects.ObjectQuery(Of Person)
            Get
                If (Me._PersonSet Is Nothing) Then
                    Me._PersonSet = MyBase.CreateQuery(Of Person)("[PersonSet]")
                End If
                Return Me._PersonSet
            End Get
        End Property
        Private _PersonSet As Global.System.Data.Objects.ObjectQuery(Of Person)
        '''<summary>
        '''There are no comments for PersonSet in the schema.
        '''</summary>
        Public Sub AddToPersonSet(ByVal person As Person)
            MyBase.AddObject("PersonSet", person)
        End Sub
    End Class
    '''<summary>
    '''There are no comments for EFTPHModel.Person in the schema.
    '''</summary>
    '''<KeyProperties>
    '''PersonID
    '''</KeyProperties>
    <Global.System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName:="EFTPHModel", Name:="Person"), _
     Global.System.Runtime.Serialization.DataContractAttribute(IsReference:=True), _
     Global.System.Serializable(), _
     Global.System.Runtime.Serialization.KnownTypeAttribute(GetType(Student)), _
     Global.System.Runtime.Serialization.KnownTypeAttribute(GetType(Instructor)), _
     Global.System.Runtime.Serialization.KnownTypeAttribute(GetType(Admin))> _
    Partial Public Class Person
        Inherits Global.System.Data.Objects.DataClasses.EntityObject
        '''<summary>
        '''Create a new Person object.
        '''</summary>
        '''<param name="personID">Initial value of PersonID.</param>
        '''<param name="lastName">Initial value of LastName.</param>
        '''<param name="firstName">Initial value of FirstName.</param>
        Public Shared Function CreatePerson(ByVal personID As Integer, ByVal lastName As String, ByVal firstName As String) As Person
            Dim person As Person = New Person
            person.PersonID = personID
            person.LastName = lastName
            person.FirstName = firstName
            Return person
        End Function
        '''<summary>
        '''There are no comments for Property PersonID in the schema.
        '''</summary>
        <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty:=True, IsNullable:=False), _
         Global.System.Runtime.Serialization.DataMemberAttribute()> _
        Public Property PersonID() As Integer
            Get
                Return Me._PersonID
            End Get
            Set(ByVal value As Integer)
                Me.OnPersonIDChanging(value)
                Me.ReportPropertyChanging("PersonID")
                Me._PersonID = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value)
                Me.ReportPropertyChanged("PersonID")
                Me.OnPersonIDChanged()
            End Set
        End Property
        Private _PersonID As Integer
        Partial Private Sub OnPersonIDChanging(ByVal value As Integer)
        End Sub
        Partial Private Sub OnPersonIDChanged()
        End Sub
        '''<summary>
        '''There are no comments for Property LastName in the schema.
        '''</summary>
        <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable:=False), _
         Global.System.Runtime.Serialization.DataMemberAttribute()> _
        Public Property LastName() As String
            Get
                Return Me._LastName
            End Get
            Set(ByVal value As String)
                Me.OnLastNameChanging(value)
                Me.ReportPropertyChanging("LastName")
                Me._LastName = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, False)
                Me.ReportPropertyChanged("LastName")
                Me.OnLastNameChanged()
            End Set
        End Property
        Private _LastName As String
        Partial Private Sub OnLastNameChanging(ByVal value As String)
        End Sub
        Partial Private Sub OnLastNameChanged()
        End Sub
        '''<summary>
        '''There are no comments for Property FirstName in the schema.
        '''</summary>
        <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable:=False), _
         Global.System.Runtime.Serialization.DataMemberAttribute()> _
        Public Property FirstName() As String
            Get
                Return Me._FirstName
            End Get
            Set(ByVal value As String)
                Me.OnFirstNameChanging(value)
                Me.ReportPropertyChanging("FirstName")
                Me._FirstName = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, False)
                Me.ReportPropertyChanged("FirstName")
                Me.OnFirstNameChanged()
            End Set
        End Property
        Private _FirstName As String
        Partial Private Sub OnFirstNameChanging(ByVal value As String)
        End Sub
        Partial Private Sub OnFirstNameChanged()
        End Sub
        '''<summary>
        '''There are no comments for Property Picture in the schema.
        '''</summary>
        <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(), _
         Global.System.Runtime.Serialization.DataMemberAttribute()> _
        Public Property Picture() As Byte()
            Get
                Return Global.System.Data.Objects.DataClasses.StructuralObject.GetValidValue(Me._Picture)
            End Get
            Set(ByVal value As Byte())
                Me.OnPictureChanging(value)
                Me.ReportPropertyChanging("Picture")
                Me._Picture = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, True)
                Me.ReportPropertyChanged("Picture")
                Me.OnPictureChanged()
            End Set
        End Property
        Private _Picture() As Byte
        Partial Private Sub OnPictureChanging(ByVal value() As Byte)
        End Sub
        Partial Private Sub OnPictureChanged()
        End Sub
    End Class
    '''<summary>
    '''There are no comments for EFTPHModel.Student in the schema.
    '''</summary>
    '''<KeyProperties>
    '''PersonID
    '''</KeyProperties>
    <Global.System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName:="EFTPHModel", Name:="Student"), _
     Global.System.Runtime.Serialization.DataContractAttribute(IsReference:=True), _
     Global.System.Serializable(), _
     Global.System.Runtime.Serialization.KnownTypeAttribute(GetType(BusinessStudent))> _
    Partial Public Class Student
        Inherits Person
        '''<summary>
        '''Create a new Student object.
        '''</summary>
        '''<param name="personID">Initial value of PersonID.</param>
        '''<param name="lastName">Initial value of LastName.</param>
        '''<param name="firstName">Initial value of FirstName.</param>
        Public Shared Function CreateStudent(ByVal personID As Integer, ByVal lastName As String, ByVal firstName As String) As Student
            Dim student As Student = New Student
            student.PersonID = personID
            student.LastName = lastName
            student.FirstName = firstName
            Return student
        End Function
        '''<summary>
        '''There are no comments for Property EnrollmentDate in the schema.
        '''</summary>
        <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(), _
         Global.System.Runtime.Serialization.DataMemberAttribute()> _
        Public Property EnrollmentDate() As Global.System.Nullable(Of Date)
            Get
                Return Me._EnrollmentDate
            End Get
            Set(ByVal value As Global.System.Nullable(Of Date))
                Me.OnEnrollmentDateChanging(value)
                Me.ReportPropertyChanging("EnrollmentDate")
                Me._EnrollmentDate = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value)
                Me.ReportPropertyChanged("EnrollmentDate")
                Me.OnEnrollmentDateChanged()
            End Set
        End Property
        Private _EnrollmentDate As Global.System.Nullable(Of Date)
        Partial Private Sub OnEnrollmentDateChanging(ByVal value As Global.System.Nullable(Of Date))
        End Sub
        Partial Private Sub OnEnrollmentDateChanged()
        End Sub
    End Class
    '''<summary>
    '''There are no comments for EFTPHModel.Instructor in the schema.
    '''</summary>
    '''<KeyProperties>
    '''PersonID
    '''</KeyProperties>
    <Global.System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName:="EFTPHModel", Name:="Instructor"), _
     Global.System.Runtime.Serialization.DataContractAttribute(IsReference:=True), _
     Global.System.Serializable()> _
    Partial Public Class Instructor
        Inherits Person
        '''<summary>
        '''Create a new Instructor object.
        '''</summary>
        '''<param name="personID">Initial value of PersonID.</param>
        '''<param name="lastName">Initial value of LastName.</param>
        '''<param name="firstName">Initial value of FirstName.</param>
        Public Shared Function CreateInstructor(ByVal personID As Integer, ByVal lastName As String, ByVal firstName As String) As Instructor
            Dim instructor As Instructor = New Instructor
            instructor.PersonID = personID
            instructor.LastName = lastName
            instructor.FirstName = firstName
            Return instructor
        End Function
        '''<summary>
        '''There are no comments for Property HireDate in the schema.
        '''</summary>
        <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(), _
         Global.System.Runtime.Serialization.DataMemberAttribute()> _
        Public Property HireDate() As Global.System.Nullable(Of Date)
            Get
                Return Me._HireDate
            End Get
            Set(ByVal value As Global.System.Nullable(Of Date))
                Me.OnHireDateChanging(value)
                Me.ReportPropertyChanging("HireDate")
                Me._HireDate = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value)
                Me.ReportPropertyChanged("HireDate")
                Me.OnHireDateChanged()
            End Set
        End Property
        Private _HireDate As Global.System.Nullable(Of Date)
        Partial Private Sub OnHireDateChanging(ByVal value As Global.System.Nullable(Of Date))
        End Sub
        Partial Private Sub OnHireDateChanged()
        End Sub
    End Class
    '''<summary>
    '''There are no comments for EFTPHModel.Admin in the schema.
    '''</summary>
    '''<KeyProperties>
    '''PersonID
    '''</KeyProperties>
    <Global.System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName:="EFTPHModel", Name:="Admin"), _
     Global.System.Runtime.Serialization.DataContractAttribute(IsReference:=True), _
     Global.System.Serializable()> _
    Partial Public Class Admin
        Inherits Person
        '''<summary>
        '''Create a new Admin object.
        '''</summary>
        '''<param name="personID">Initial value of PersonID.</param>
        '''<param name="lastName">Initial value of LastName.</param>
        '''<param name="firstName">Initial value of FirstName.</param>
        Public Shared Function CreateAdmin(ByVal personID As Integer, ByVal lastName As String, ByVal firstName As String) As Admin
            Dim admin As Admin = New Admin
            admin.PersonID = personID
            admin.LastName = lastName
            admin.FirstName = firstName
            Return admin
        End Function
        '''<summary>
        '''There are no comments for Property AdminDate in the schema.
        '''</summary>
        <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(), _
         Global.System.Runtime.Serialization.DataMemberAttribute()> _
        Public Property AdminDate() As Global.System.Nullable(Of Date)
            Get
                Return Me._AdminDate
            End Get
            Set(ByVal value As Global.System.Nullable(Of Date))
                Me.OnAdminDateChanging(value)
                Me.ReportPropertyChanging("AdminDate")
                Me._AdminDate = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value)
                Me.ReportPropertyChanged("AdminDate")
                Me.OnAdminDateChanged()
            End Set
        End Property
        Private _AdminDate As Global.System.Nullable(Of Date)
        Partial Private Sub OnAdminDateChanging(ByVal value As Global.System.Nullable(Of Date))
        End Sub
        Partial Private Sub OnAdminDateChanged()
        End Sub
    End Class
    '''<summary>
    '''There are no comments for EFTPHModel.BusinessStudent in the schema.
    '''</summary>
    '''<KeyProperties>
    '''PersonID
    '''</KeyProperties>
    <Global.System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName:="EFTPHModel", Name:="BusinessStudent"), _
     Global.System.Runtime.Serialization.DataContractAttribute(IsReference:=True), _
     Global.System.Serializable()> _
    Partial Public Class BusinessStudent
        Inherits Student
        '''<summary>
        '''Create a new BusinessStudent object.
        '''</summary>
        '''<param name="personID">Initial value of PersonID.</param>
        '''<param name="lastName">Initial value of LastName.</param>
        '''<param name="firstName">Initial value of FirstName.</param>
        Public Shared Function CreateBusinessStudent(ByVal personID As Integer, ByVal lastName As String, ByVal firstName As String) As BusinessStudent
            Dim businessStudent As BusinessStudent = New BusinessStudent
            businessStudent.PersonID = personID
            businessStudent.LastName = lastName
            businessStudent.FirstName = firstName
            Return businessStudent
        End Function
        '''<summary>
        '''There are no comments for Property BusinessCredits in the schema.
        '''</summary>
        <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(), _
         Global.System.Runtime.Serialization.DataMemberAttribute()> _
        Public Property BusinessCredits() As String
            Get
                Return Me._BusinessCredits
            End Get
            Set(ByVal value As String)
                Me.OnBusinessCreditsChanging(value)
                Me.ReportPropertyChanging("BusinessCredits")
                Me._BusinessCredits = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, True)
                Me.ReportPropertyChanged("BusinessCredits")
                Me.OnBusinessCreditsChanged()
            End Set
        End Property
        Private _BusinessCredits As String
        Partial Private Sub OnBusinessCreditsChanging(ByVal value As String)
        End Sub
        Partial Private Sub OnBusinessCreditsChanged()
        End Sub
    End Class
End Namespace