'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.42
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On



Namespace Microsoft.ServiceModel.Samples
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute([Namespace]:="http://Microsoft.ServiceModel.Samples", ConfigurationName:="Microsoft.ServiceModel.Samples.ICalculatorConcurrency")>  _
    Public Interface ICalculatorConcurrency
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://Microsoft.ServiceModel.Samples/ICalculator/Add", ReplyAction:="http://Microsoft.ServiceModel.Samples/ICalculator/AddResponse")>  _
        Function Add(ByVal n1 As Double, ByVal n2 As Double) As Double
        
        <System.ServiceModel.OperationContractAttribute(AsyncPattern:=true, Action:="http://Microsoft.ServiceModel.Samples/ICalculator/Add", ReplyAction:="http://Microsoft.ServiceModel.Samples/ICalculator/AddResponse")>  _
        Function BeginAdd(ByVal n1 As Double, ByVal n2 As Double, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
        
        Function EndAdd(ByVal result As System.IAsyncResult) As Double
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://Microsoft.ServiceModel.Samples/ICalculator/Subtract", ReplyAction:="http://Microsoft.ServiceModel.Samples/ICalculator/SubtractResponse")>  _
        Function Subtract(ByVal n1 As Double, ByVal n2 As Double) As Double
        
        <System.ServiceModel.OperationContractAttribute(AsyncPattern:=true, Action:="http://Microsoft.ServiceModel.Samples/ICalculator/Subtract", ReplyAction:="http://Microsoft.ServiceModel.Samples/ICalculator/SubtractResponse")>  _
        Function BeginSubtract(ByVal n1 As Double, ByVal n2 As Double, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
        
        Function EndSubtract(ByVal result As System.IAsyncResult) As Double
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://Microsoft.ServiceModel.Samples/ICalculator/Multiply", ReplyAction:="http://Microsoft.ServiceModel.Samples/ICalculator/MultiplyResponse")>  _
        Function Multiply(ByVal n1 As Double, ByVal n2 As Double) As Double
        
        <System.ServiceModel.OperationContractAttribute(AsyncPattern:=true, Action:="http://Microsoft.ServiceModel.Samples/ICalculator/Multiply", ReplyAction:="http://Microsoft.ServiceModel.Samples/ICalculator/MultiplyResponse")>  _
        Function BeginMultiply(ByVal n1 As Double, ByVal n2 As Double, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
        
        Function EndMultiply(ByVal result As System.IAsyncResult) As Double
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://Microsoft.ServiceModel.Samples/ICalculator/Divide", ReplyAction:="http://Microsoft.ServiceModel.Samples/ICalculator/DivideResponse")>  _
        Function Divide(ByVal n1 As Double, ByVal n2 As Double) As Double
        
        <System.ServiceModel.OperationContractAttribute(AsyncPattern:=true, Action:="http://Microsoft.ServiceModel.Samples/ICalculator/Divide", ReplyAction:="http://Microsoft.ServiceModel.Samples/ICalculator/DivideResponse")>  _
        Function BeginDivide(ByVal n1 As Double, ByVal n2 As Double, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
        
        Function EndDivide(ByVal result As System.IAsyncResult) As Double
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://Microsoft.ServiceModel.Samples/ICalculatorConcurrency/GetConcurrencyMode", ReplyAction:="http://Microsoft.ServiceModel.Samples/ICalculatorConcurrency/GetConcurrencyModeRe"& _ 
            "sponse")>  _
        Function GetConcurrencyMode() As String
        
        <System.ServiceModel.OperationContractAttribute(AsyncPattern:=true, Action:="http://Microsoft.ServiceModel.Samples/ICalculatorConcurrency/GetConcurrencyMode", ReplyAction:="http://Microsoft.ServiceModel.Samples/ICalculatorConcurrency/GetConcurrencyModeRe"& _ 
            "sponse")>  _
        Function BeginGetConcurrencyMode(ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
        
        Function EndGetConcurrencyMode(ByVal result As System.IAsyncResult) As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://Microsoft.ServiceModel.Samples/ICalculatorConcurrency/GetOperationCount", ReplyAction:="http://Microsoft.ServiceModel.Samples/ICalculatorConcurrency/GetOperationCountRes"& _ 
            "ponse")>  _
        Function GetOperationCount() As Integer
        
        <System.ServiceModel.OperationContractAttribute(AsyncPattern:=true, Action:="http://Microsoft.ServiceModel.Samples/ICalculatorConcurrency/GetOperationCount", ReplyAction:="http://Microsoft.ServiceModel.Samples/ICalculatorConcurrency/GetOperationCountRes"& _ 
            "ponse")>  _
        Function BeginGetOperationCount(ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
        
        Function EndGetOperationCount(ByVal result As System.IAsyncResult) As Integer
    End Interface
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")>  _
    Public Interface ICalculatorConcurrencyChannel
        Inherits Microsoft.ServiceModel.Samples.ICalculatorConcurrency, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")>  _
    Partial Public Class CalculatorConcurrencyClient
        Inherits System.ServiceModel.ClientBase(Of Microsoft.ServiceModel.Samples.ICalculatorConcurrency)
        Implements Microsoft.ServiceModel.Samples.ICalculatorConcurrency
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Function Add(ByVal n1 As Double, ByVal n2 As Double) As Double Implements Microsoft.ServiceModel.Samples.ICalculatorConcurrency.Add
            Return MyBase.Channel.Add(n1, n2)
        End Function
        
        Public Function BeginAdd(ByVal n1 As Double, ByVal n2 As Double, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult Implements Microsoft.ServiceModel.Samples.ICalculatorConcurrency.BeginAdd
            Return MyBase.Channel.BeginAdd(n1, n2, callback, asyncState)
        End Function
        
        Public Function EndAdd(ByVal result As System.IAsyncResult) As Double Implements Microsoft.ServiceModel.Samples.ICalculatorConcurrency.EndAdd
            Return MyBase.Channel.EndAdd(result)
        End Function
        
        Public Function Subtract(ByVal n1 As Double, ByVal n2 As Double) As Double Implements Microsoft.ServiceModel.Samples.ICalculatorConcurrency.Subtract
            Return MyBase.Channel.Subtract(n1, n2)
        End Function
        
        Public Function BeginSubtract(ByVal n1 As Double, ByVal n2 As Double, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult Implements Microsoft.ServiceModel.Samples.ICalculatorConcurrency.BeginSubtract
            Return MyBase.Channel.BeginSubtract(n1, n2, callback, asyncState)
        End Function
        
        Public Function EndSubtract(ByVal result As System.IAsyncResult) As Double Implements Microsoft.ServiceModel.Samples.ICalculatorConcurrency.EndSubtract
            Return MyBase.Channel.EndSubtract(result)
        End Function
        
        Public Function Multiply(ByVal n1 As Double, ByVal n2 As Double) As Double Implements Microsoft.ServiceModel.Samples.ICalculatorConcurrency.Multiply
            Return MyBase.Channel.Multiply(n1, n2)
        End Function
        
        Public Function BeginMultiply(ByVal n1 As Double, ByVal n2 As Double, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult Implements Microsoft.ServiceModel.Samples.ICalculatorConcurrency.BeginMultiply
            Return MyBase.Channel.BeginMultiply(n1, n2, callback, asyncState)
        End Function
        
        Public Function EndMultiply(ByVal result As System.IAsyncResult) As Double Implements Microsoft.ServiceModel.Samples.ICalculatorConcurrency.EndMultiply
            Return MyBase.Channel.EndMultiply(result)
        End Function
        
        Public Function Divide(ByVal n1 As Double, ByVal n2 As Double) As Double Implements Microsoft.ServiceModel.Samples.ICalculatorConcurrency.Divide
            Return MyBase.Channel.Divide(n1, n2)
        End Function
        
        Public Function BeginDivide(ByVal n1 As Double, ByVal n2 As Double, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult Implements Microsoft.ServiceModel.Samples.ICalculatorConcurrency.BeginDivide
            Return MyBase.Channel.BeginDivide(n1, n2, callback, asyncState)
        End Function
        
        Public Function EndDivide(ByVal result As System.IAsyncResult) As Double Implements Microsoft.ServiceModel.Samples.ICalculatorConcurrency.EndDivide
            Return MyBase.Channel.EndDivide(result)
        End Function
        
        Public Function GetConcurrencyMode() As String Implements Microsoft.ServiceModel.Samples.ICalculatorConcurrency.GetConcurrencyMode
            Return MyBase.Channel.GetConcurrencyMode
        End Function
        
        Public Function BeginGetConcurrencyMode(ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult Implements Microsoft.ServiceModel.Samples.ICalculatorConcurrency.BeginGetConcurrencyMode
            Return MyBase.Channel.BeginGetConcurrencyMode(callback, asyncState)
        End Function
        
        Public Function EndGetConcurrencyMode(ByVal result As System.IAsyncResult) As String Implements Microsoft.ServiceModel.Samples.ICalculatorConcurrency.EndGetConcurrencyMode
            Return MyBase.Channel.EndGetConcurrencyMode(result)
        End Function
        
        Public Function GetOperationCount() As Integer Implements Microsoft.ServiceModel.Samples.ICalculatorConcurrency.GetOperationCount
            Return MyBase.Channel.GetOperationCount
        End Function
        
        Public Function BeginGetOperationCount(ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult Implements Microsoft.ServiceModel.Samples.ICalculatorConcurrency.BeginGetOperationCount
            Return MyBase.Channel.BeginGetOperationCount(callback, asyncState)
        End Function
        
        Public Function EndGetOperationCount(ByVal result As System.IAsyncResult) As Integer Implements Microsoft.ServiceModel.Samples.ICalculatorConcurrency.EndGetOperationCount
            Return MyBase.Channel.EndGetOperationCount(result)
        End Function
    End Class
End Namespace
