# ==++==
#
#   
#    Copyright (c) 2006 Microsoft Corporation.  All rights reserved.
#   
#    The use and distribution terms for this software are contained in the file
#    named license.txt, which can be found in the root of this distribution.
#    By using this software in any fashion, you are agreeing to be bound by the
#    terms of this license.
#   
#    You must not remove this notice, or any other, from this software.
#   
#
# ==--==

CC=cl
CC_OPTS=/nologo /DWIN32 /Zi /Od /W3 /WX 
MAIN_FILE=xrun
xrun : $(ROTOR_DIR)\tests\harness\xrun\xrun.c 
	-mkdir $(ROTOR_DIR)\tests\harness\xrun\obj$(BUILD_ALT_DIR)
	$(CC) /nologo /DWIN32 /Zi /Od /W3 /WX  $(ROTOR_DIR)\tests\harness\xrun\xrun.c /Fe$(ROTOR_DIR)\tests\harness\xrun\obj$(BUILD_ALT_DIR)\xrun \
!if "$(MSVCDIR)"==""
	      /I$(LKGVC_DIR)\public\sdk\inc /I$(LKGVC_DIR)\public\vc\inc \
          /link /LIBPATH:$(LKGVC_DIR)\public\sdk\lib\i386 \
          /LIBPATH:$(LKGVC_DIR)\public\vc\lib\i386
!endif
