# ==++==
#
#   
#    Copyright (c) 2006 Microsoft Corporation.  All rights reserved.
#   
#    The use and distribution terms for this software are contained in the file
#    named license.txt, which can be found in the root of this distribution.
#    By using this software in any fashion, you are agreeing to be bound by the
#    terms of this license.
#   
#    You must not remove this notice, or any other, from this software.
#   
#
# ==--==

GCC=gcc
GCC_OPTS=-g -Wall $(C_DEFINES) -o  
MAIN_FILE=xrun
ifeq "$(PLATFORM_OS)" "freebsd"
GCC_OPTS=-pthread -g -Wall $(C_DEFINES) -o
else # is FreeBSD?
ifeq "$(PLATFORM_OS)" "darwin"
endif # Darwin if
endif # FreeBSD if

xrun : $(ROTOR_DIR)/tests/harness/xrun/xrun.c
	-mkdir  $(ROTOR_DIR)/tests/harness/xrun/obj$(BUILD_ALT_DIR)
	$(GCC) $(GCC_OPTS) $(ROTOR_DIR)/tests/harness/xrun/obj$(BUILD_ALT_DIR)/xrun  $(ROTOR_DIR)/tests/harness/xrun/xrun.c 
