//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4900
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.Samples.ExtendedProtectionPolicy.ServiceReference
{


    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName = "ServiceReference.IGetKey")]
    public interface IGetKey
    {

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IGetKey/GetKeyFromPasscode", ReplyAction = "http://tempuri.org/IGetKey/GetKeyFromPasscodeResponse")]
        string GetKeyFromPasscode(string passCode);
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface IGetKeyChannel : Microsoft.Samples.ExtendedProtectionPolicy.ServiceReference.IGetKey, System.ServiceModel.IClientChannel
    {
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class GetKeyClient : System.ServiceModel.ClientBase<Microsoft.Samples.ExtendedProtectionPolicy.ServiceReference.IGetKey>, Microsoft.Samples.ExtendedProtectionPolicy.ServiceReference.IGetKey
    {

        public GetKeyClient()
        {
        }

        public GetKeyClient(string endpointConfigurationName) :
            base(endpointConfigurationName)
        {
        }

        public GetKeyClient(string endpointConfigurationName, string remoteAddress) :
            base(endpointConfigurationName, remoteAddress)
        {
        }

        public GetKeyClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) :
            base(endpointConfigurationName, remoteAddress)
        {
        }

        public GetKeyClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) :
            base(binding, remoteAddress)
        {
        }

        public string GetKeyFromPasscode(string passCode)
        {
            return base.Channel.GetKeyFromPasscode(passCode);
        }
    }
}

