// ==++==
// 
//   
//    Copyright (c) 2006 Microsoft Corporation.  All rights reserved.
//   
//    The use and distribution terms for this software are contained in the file
//    named license.txt, which can be found in the root of this distribution.
//    By using this software in any fashion, you are agreeing to be bound by the
//    terms of this license.
//   
//    You must not remove this notice, or any other, from this software.
//   
// 
// ==--==
/* ------------------------------------------------------------------------- *
 * Common Language Runtime Verification Event Handler Interface
 * ------------------------------------------------------------------------- */

/* ------------------------------------------------------------------------- *
 * Imported types
 * ------------------------------------------------------------------------- */


typedef _VerError VEContext;

/* ------------------------------------------------------------------------- *
 * Forward declarations
 * ------------------------------------------------------------------------- */

interface IVEHandler;


/* ------------------------------------------------------------------------- *
 * Library defintion
 * ------------------------------------------------------------------------- */

[
  uuid(856CA1B0-7DAB-11d3-ACEC-00C04F86C309),
  version(1.0),
  helpstring("Common Language Runtime Verification Event Handler 1.0 Type Library")
]
library VEHandlerLib
{
    importlib("STDOLE2.TLB");

	[
        uuid(856CA1B1-7DAB-11d3-ACEC-00C04F86C309)
	]
	coclass VEHandlerClass
	{
		[default] interface IVEHandler;
	};
    
};

/* ------------------------------------------------------------------------- *
 * IVEHandler interface
 * ------------------------------------------------------------------------- */
[
 object,
 uuid(856CA1B2-7DAB-11d3-ACEC-00C04F86C309),
 pointer_default(unique)
]
interface IVEHandler : IUnknown
{
    HRESULT VEHandler(
			[in] HRESULT VECode,
			[in] VEContext Context,
			[in] SAFEARRAY(VARIANT) psa);
	HRESULT SetReporterFtn(
			[in] __int64 lFnPtr);

};

