//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.Runtime.Serialization.ContractNamespaceAttribute("http://Microsoft.ServiceModel.Samples", ClrNamespace="Microsoft.ServiceModel.Samples")]

namespace Microsoft.ServiceModel.Samples
{
    using System.Runtime.Serialization;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Microsoft.ServiceModel.Samples.ComplexNumberWithMagnitude))]
    public partial class ComplexNumber : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private double imaginaryField;
        
        private double realField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double imaginary
        {
            get
            {
                return this.imaginaryField;
            }
            set
            {
                this.imaginaryField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double real
        {
            get
            {
                return this.realField;
            }
            set
            {
                this.realField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class ComplexNumberWithMagnitude : Microsoft.ServiceModel.Samples.ComplexNumber
    {
        
        private double MagnitudeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Magnitude
        {
            get
            {
                return this.MagnitudeField;
            }
            set
            {
                this.MagnitudeField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://Microsoft.ServiceModel.Samples", ConfigurationName="Microsoft.ServiceModel.Samples.IDataContractCalculator")]
    public interface IDataContractCalculator
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Microsoft.ServiceModel.Samples/IDataContractCalculator/Add", ReplyAction="http://Microsoft.ServiceModel.Samples/IDataContractCalculator/AddResponse")]
        Microsoft.ServiceModel.Samples.ComplexNumber Add(Microsoft.ServiceModel.Samples.ComplexNumber n1, Microsoft.ServiceModel.Samples.ComplexNumber n2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Microsoft.ServiceModel.Samples/IDataContractCalculator/Subtract", ReplyAction="http://Microsoft.ServiceModel.Samples/IDataContractCalculator/SubtractResponse")]
        Microsoft.ServiceModel.Samples.ComplexNumber Subtract(Microsoft.ServiceModel.Samples.ComplexNumber n1, Microsoft.ServiceModel.Samples.ComplexNumber n2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Microsoft.ServiceModel.Samples/IDataContractCalculator/Multiply", ReplyAction="http://Microsoft.ServiceModel.Samples/IDataContractCalculator/MultiplyResponse")]
        Microsoft.ServiceModel.Samples.ComplexNumber Multiply(Microsoft.ServiceModel.Samples.ComplexNumber n1, Microsoft.ServiceModel.Samples.ComplexNumber n2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Microsoft.ServiceModel.Samples/IDataContractCalculator/Divide", ReplyAction="http://Microsoft.ServiceModel.Samples/IDataContractCalculator/DivideResponse")]
        Microsoft.ServiceModel.Samples.ComplexNumber Divide(Microsoft.ServiceModel.Samples.ComplexNumber n1, Microsoft.ServiceModel.Samples.ComplexNumber n2);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface IDataContractCalculatorChannel : Microsoft.ServiceModel.Samples.IDataContractCalculator, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class DataContractCalculatorClient : System.ServiceModel.ClientBase<Microsoft.ServiceModel.Samples.IDataContractCalculator>, Microsoft.ServiceModel.Samples.IDataContractCalculator
    {
        
        public DataContractCalculatorClient()
        {
        }
        
        public DataContractCalculatorClient(string endpointConfigurationName) : 
                base(endpointConfigurationName)
        {
        }
        
        public DataContractCalculatorClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public DataContractCalculatorClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public DataContractCalculatorClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public Microsoft.ServiceModel.Samples.ComplexNumber Add(Microsoft.ServiceModel.Samples.ComplexNumber n1, Microsoft.ServiceModel.Samples.ComplexNumber n2)
        {
            return base.Channel.Add(n1, n2);
        }
        
        public Microsoft.ServiceModel.Samples.ComplexNumber Subtract(Microsoft.ServiceModel.Samples.ComplexNumber n1, Microsoft.ServiceModel.Samples.ComplexNumber n2)
        {
            return base.Channel.Subtract(n1, n2);
        }
        
        public Microsoft.ServiceModel.Samples.ComplexNumber Multiply(Microsoft.ServiceModel.Samples.ComplexNumber n1, Microsoft.ServiceModel.Samples.ComplexNumber n2)
        {
            return base.Channel.Multiply(n1, n2);
        }
        
        public Microsoft.ServiceModel.Samples.ComplexNumber Divide(Microsoft.ServiceModel.Samples.ComplexNumber n1, Microsoft.ServiceModel.Samples.ComplexNumber n2)
        {
            return base.Channel.Divide(n1, n2);
        }
    }
}

