// ==++==
//
//   
//    Copyright (c) 2006 Microsoft Corporation.  All rights reserved.
//   
//    The use and distribution terms for this software are contained in the file
//    named license.txt, which can be found in the root of this distribution.
//    By using this software in any fashion, you are agreeing to be bound by the
//    terms of this license.
//   
//    You must not remove this notice, or any other, from this software.
//   
//
// ==--==
// ===========================================================================
// File: errors.h
//
// Contains a list of all the warnings and errors in the compiler.
//
// ===========================================================================

#if !defined(ERRORDEF) || !defined(WARNDEF) || !defined(FATALDEF) || !defined(OLDWARN)
#error Must define ERRORDEF macro before including errors.h
#endif

// NOTE:  Warnings, errors, and fatal errors are determined by the
//        various macros.  ERRORDEF = ERROR_ERROR, FATALDEF = ERROR_FATAL
//        WARNDEF and OLDWARN = ERROR_WARNING
//        warning level value as follows:
//
//          0   = ERROR_ERROR
//          >0  = ERROR_WARNING
//          -1  = ERROR_FATAL
//
//     Error  Warning
//     Number, Level,      Error name,                    Resource name
FATALDEF(   1,    InternalError,                  IDS_InternalError)

FATALDEF(   3,    NoMemory,                       IDS_NoMemory)
ERRORDEF(   4,    WarningAsError,                 IDS_WarningAsError)
ERRORDEF(   5,    MissingOptionArg,               IDS_MissingOptionArg)
ERRORDEF(   6,    NoMetadataFile,                 IDS_NoMetadataFile)
FATALDEF(   7,    ComPlusInit,                    IDS_ComPlusInit)
FATALDEF(   8,    MetadataImportFailure,          IDS_MetadataImportFailure)
FATALDEF(   9,    MetadataCantOpenFile,           IDS_MetadataCantOpenFile)
//ERRORDEF(  10,    NamespaceTypeConflict,          IDS_NamespaceTypeConflict)
ERRORDEF(  11,    CantImportBase,                 IDS_CantImportBase)
ERRORDEF(  12,    NoTypeDef,                      IDS_NoTypeDef)
FATALDEF(  13,    MetadataEmitFailure,            IDS_MetadataEmitFailure)
FATALDEF(  14,    RequiredFileNotFound,           IDS_RequiredFileNotFound)
ERRORDEF(  15,    ClassNameTooLong,               IDS_ClassNameTooLong)
ERRORDEF(  16,    OutputWriteFailed,              IDS_OutputWriteFailed)
ERRORDEF(  17,    MultipleEntryPoints,            IDS_MultipleEntryPoints)
ERRORDEF(  18,    UnimplementedOp,                IDS_UnimplementedOp)
ERRORDEF(  19,    BadBinaryOps,                   IDS_BadBinaryOps)
ERRORDEF(  20,    IntDivByZero,                   IDS_IntDivByZero)
ERRORDEF(  21,    BadIndexLHS,                    IDS_BadIndexLHS)
ERRORDEF(  22,    BadIndexCount,                  IDS_BadIndexCount)
ERRORDEF(  23,    BadUnaryOp,                     IDS_BadUnaryOp)

ERRORDEF(  25,    NoStdLib,                       IDS_NoStdLib)
ERRORDEF(  26,    ThisInStaticMeth,               IDS_ThisInStaticMeth)
ERRORDEF(  27,    ThisInBadContext,               IDS_ThisInBadContext)
WARNDEF(   28, 4, InvalidMainSig,                 IDS_InvalidMainSig)
ERRORDEF(  29,    NoImplicitConv,                 IDS_NoImplicitConv)
ERRORDEF(  30,    NoExplicitConv,                 IDS_NoExplicitConv)
ERRORDEF(  31,    ConstOutOfRange,                IDS_ConstOutOfRange)
//ERRORDEF(  32,    IncBuildWrite,                  IDS_IncBuildWrite)
//ERRORDEF(  33,    IncBuildWriteIO,                IDS_IncBuildWriteIO)
ERRORDEF(  34,    AmbigBinaryOps,                 IDS_AmbigBinaryOps)
ERRORDEF(  35,    AmbigUnaryOp,                   IDS_AmbigUnaryOp)
ERRORDEF(  36,    InAttrOnOutParam,               IDS_InAttrOnOutParam)
ERRORDEF(  37,    ValueCantBeNull,                IDS_ValueCantBeNull)
ERRORDEF(  38,    WrongNestedThis,                IDS_WrongNestedThis)
ERRORDEF(  39,    NoExplicitBuiltinConv,          IDS_NoExplicitBuiltinConv)

FATALDEF(  40,    DebugInit,                      IDS_DebugInit)
FATALDEF(  41,    DebugEmitFailure,               IDS_DebugEmitFailure)
FATALDEF(  42,    DebugInitFile,                  IDS_DebugInitFile)
FATALDEF(  43,    BadPDBFormat,                   IDS_BadPDBFormat)

ERRORDEF(  50,    BadVisReturnType,               IDS_BadVisReturnType)
ERRORDEF(  51,    BadVisParamType,                IDS_BadVisParamType)
ERRORDEF(  52,    BadVisFieldType,                IDS_BadVisFieldType)
ERRORDEF(  53,    BadVisPropertyType,             IDS_BadVisPropertyType)
ERRORDEF(  54,    BadVisIndexerReturn,            IDS_BadVisIndexerReturn)
ERRORDEF(  55,    BadVisIndexerParam,             IDS_BadVisIndexerParam)
ERRORDEF(  56,    BadVisOpReturn,                 IDS_BadVisOpReturn)
ERRORDEF(  57,    BadVisOpParam,                  IDS_BadVisOpParam)
ERRORDEF(  58,    BadVisDelegateReturn,           IDS_BadVisDelegateReturn)
ERRORDEF(  59,    BadVisDelegateParam,            IDS_BadVisDelegateParam)
ERRORDEF(  60,    BadVisBaseClass,                IDS_BadVisBaseClass)
ERRORDEF(  61,    BadVisBaseInterface,            IDS_BadVisBaseInterface)
ERRORDEF(  65,    EventNeedsBothAccessors,        IDS_EventNeedsBothAccessors)
ERRORDEF(  66,    EventNotDelegate,               IDS_EventNotDelegate)
WARNDEF(   67, 3, UnreferencedEvent,              IDS_UnreferencedEvent)
ERRORDEF(  68,    InterfaceEventInitializer,      IDS_InterfaceEventInitializer)
ERRORDEF(  69,    EventPropertyInInterface,       IDS_EventPropertyInInterface)
ERRORDEF(  70,    BadEventUsage,                  IDS_BadEventUsage)
ERRORDEF(  71,    ExplicitEventFieldImpl,         IDS_ExplicitEventFieldImpl)
ERRORDEF(  72,    CantOverrideNonEvent,           IDS_CantOverrideNonEvent)
ERRORDEF(  73,    AddRemoveMustHaveBody,          IDS_AddRemoveMustHaveBody)
ERRORDEF(  74,    AbstractEventInitializer,       IDS_AbstractEventInitializer)
ERRORDEF(  75,    PossibleBadNegCast,             IDS_PossibleBadNegCast)
ERRORDEF(  76,    ReservedEnumerator,             IDS_ReservedEnumerator)
ERRORDEF(  77,    AsMustHaveReferenceType,        IDS_AsMustHaveReferenceType)
WARNDEF(   78, 4, LowercaseEllSuffix,             IDS_LowercaseEllSuffix)
ERRORDEF(  79,    BadEventUsageNoField,           IDS_BadEventUsageNoField)
ERRORDEF(  80,    ConstraintOnlyAllowedOnGenericDecl,
                                                  IDS_ConstraintOnlyAllowedOnGenericDecl)
ERRORDEF(  81,    TypeParamMustBeIdentifier,      IDS_TypeParamMustBeIdentifier)

ERRORDEF( 100,    DuplicateParamName,             IDS_DuplicateParamName)
ERRORDEF( 101,    DuplicateNameInNS,              IDS_DuplicateNameInNS)
ERRORDEF( 102,    DuplicateNameInClass,           IDS_DuplicateNameInClass)
ERRORDEF( 103,    NameNotInContext,               IDS_NameNotInContext)
ERRORDEF( 104,    AmbigContext,                   IDS_AmbigContext)
WARNDEF(  105, 3, DuplicateUsing,                 IDS_DuplicateUsing)
ERRORDEF( 106,    BadMemberFlag,                  IDS_BadMemberFlag)
ERRORDEF( 107,    BadMemberProtection,            IDS_BadMemberProtection)
WARNDEF(  108, 2, NewRequired,                    IDS_NewRequired)
WARNDEF(  109, 4, NewNotRequired,                 IDS_NewNotRequired)
ERRORDEF( 110,    CircConstValue,                 IDS_CircConstValue)
ERRORDEF( 111,    MemberAlreadyExists,            IDS_MemberAlreadyExists)
ERRORDEF( 112,    StaticNotVirtual,               IDS_StaticNotVirtual)
ERRORDEF( 113,    OverrideNotNew,                 IDS_OverrideNotNew)
WARNDEF(  114, 2, NewOrOverrideExpected,          IDS_NewOrOverrideExpected)
ERRORDEF( 115,    OverrideNotExpected,            IDS_OverrideNotExpected)
ERRORDEF( 116,    NamespaceUnexpected,            IDS_NamespaceUnexpected)
ERRORDEF( 117,    NoSuchMember,                   IDS_NoSuchMember)
ERRORDEF( 118,    BadSKknown,                     IDS_BadSKknown)
ERRORDEF( 119,    BadSKunknown,                   IDS_BadSKunknown)
ERRORDEF( 120,    ObjectRequired,                 IDS_ObjectRequired)
ERRORDEF( 121,    AmbigCall,                      IDS_AmbigCall)
ERRORDEF( 122,    BadAccess,                      IDS_BadAccess)
ERRORDEF( 123,    MethDelegateMismatch,           IDS_MethDelegateMismatch)
//ERRORDEF( 124,    InvalidName,                    IDS_InvalidName)         // Not Used
//ERRORDEF( 125,    RetBadType,                     IDS_RetBadType)          // Not Used
ERRORDEF( 126,    RetObjectRequired,              IDS_RetObjectRequired)
ERRORDEF( 127,    RetNoObjectRequired,            IDS_RetNoObjectRequired)
ERRORDEF( 128,    LocalDuplicate,                 IDS_LocalDuplicate)
//ERRORDEF( 129,    LocalShadow,                    IDS_LocalShadow)         // Not used
//ERRORDEF( 130,    LocalShadowLocal,               IDS_LocalShadowLocal)    // Not used
ERRORDEF( 131,    AssgLvalueExpected,             IDS_AssgLvalueExpected)
ERRORDEF( 132,    StaticConstParam,               IDS_StaticConstParam)
ERRORDEF( 133,    NotConstantExpression,          IDS_NotConstantExpression)
ERRORDEF( 134,    NotNullConstRefField,           IDS_NotNullConstRefField)
//ERRORDEF( 134,    IllegalQualifiedNamespace,      IDS_IllegalQualifiedNamespace)
ERRORDEF( 135,    NameIllegallyOverrides,         IDS_NameIllegallyOverrides)
ERRORDEF( 136,    LocalIllegallyOverrides,        IDS_LocalIllegallyOverrides)
//ERRORDEF( 137,    BadUsingAlias,                  IDS_BadUsingAlias)
ERRORDEF( 138,    BadUsingNamespace,              IDS_BadUsingNamespace)
ERRORDEF( 139,    NoBreakOrCont,                  IDS_NoBreakOrCont)
ERRORDEF( 140,    DuplicateLabel,                 IDS_DuplicateLabel)
ERRORDEF( 141,    FeatureNYI,                     IDS_FeatureNYI)
//ERRORDEF( 142,    NoDefaultConstructor,           IDS_NoDefaultConstructor)    // Not Used
ERRORDEF( 143,    NoConstructors,                 IDS_NoConstructors)
ERRORDEF( 144,    NoNewAbstract,                  IDS_NoNewAbstract)
ERRORDEF( 145,    ConstValueRequired,             IDS_ConstValueRequired)
ERRORDEF( 146,    CircularBase,                   IDS_CircularBase)
//ERRORDEF( 147,    NoThis,                         IDS_NoThis)              // Not Used
ERRORDEF( 148,    BadDelegateConstructor,         IDS_BadDelegateConstructor)
ERRORDEF( 149,    MethodNameExpected,             IDS_MethodNameExpected)
ERRORDEF( 150,    ConstantExpected,               IDS_ConstantExpected)
ERRORDEF( 151,    IntegralTypeValueExpected,      IDS_IntegralTypeValueExpected)
ERRORDEF( 152,    DuplicateCaseLabel,             IDS_DuplicateCaseLabel)
ERRORDEF( 153,    InvalidGotoCase,                IDS_InvalidGotoCase)
ERRORDEF( 154,    PropertyLacksGet,               IDS_PropertyLacksGet)
ERRORDEF( 155,    BadExceptionType,               IDS_BadExceptionType)
ERRORDEF( 156,    BadEmptyThrow,                  IDS_BadEmptyThrow)
ERRORDEF( 157,    BadFinallyLeave,                IDS_BadFinallyLeave)
ERRORDEF( 158,    LabelShadow,                    IDS_LabelShadow)
ERRORDEF( 159,    LabelNotFound,                  IDS_LabelNotFound)
ERRORDEF( 160,    UnreachableCatch,               IDS_UnreachableCatch)
ERRORDEF( 161,    ReturnExpected,                 IDS_ReturnExpected)
WARNDEF(  162, 2, UnreachableCode,                IDS_UnreachableCode)
ERRORDEF( 163,    SwitchFallThrough,              IDS_SwitchFallThrough)
WARNDEF(  164, 2, UnreferencedLabel,              IDS_UnreferencedLabel)
ERRORDEF( 165,    UseDefViolation,                IDS_UseDefViolation)
//ERRORDEF( 166,    SwitchFallInto,                 IDS_SwitchFallInto)      // Not Used
ERRORDEF( 167,    NoInvoke,                       IDS_NoInvoke)
WARNDEF(  168, 3, UnreferencedVar,                IDS_UnreferencedVar)
WARNDEF(  169, 3, UnreferencedField,              IDS_UnreferencedField)
ERRORDEF( 170,    UseDefViolationField,           IDS_UseDefViolationField)
ERRORDEF( 171,    UnassignedThis,                 IDS_UnassignedThis)
ERRORDEF( 172,    AmbigQM,                        IDS_AmbigQM)
ERRORDEF( 173,    InvalidQM,                      IDS_InvalidQM)
ERRORDEF( 174,    NoBaseClass,                    IDS_NoBaseClass)
ERRORDEF( 175,    BaseIllegal,                    IDS_BaseIllegal)
ERRORDEF( 176,    ObjectProhibited,               IDS_ObjectProhibited)
ERRORDEF( 177,    ParamUnassigned,                IDS_ParamUnassigned)
ERRORDEF( 178,    InvalidArray,                   IDS_InvalidArray)
ERRORDEF( 179,    ExternHasBody,                  IDS_ExternHasBody)
ERRORDEF( 180,    AbstractAndExtern,              IDS_AbstractAndExtern)
//ERRORDEF( 181,    UnknownAttribute,               IDS_UnknownAttribute)
ERRORDEF( 182,    BadAttributeParam,              IDS_BadAttributeParam)
WARNDEF(  183, 1, IsAlwaysTrue,                   IDS_IsAlwaysTrue)
WARNDEF(  184, 1, IsAlwaysFalse,                  IDS_IsAlwaysFalse)
ERRORDEF( 185,    LockNeedsReference,             IDS_LockNeedsReference)
ERRORDEF( 186,    NullNotValid,                   IDS_NullNotValid)
//ERRORDEF( 187,    NoSuchOperator,                 IDS_NoSuchOperator)
ERRORDEF( 188,    UseDefViolationThis,            IDS_UseDefViolationThis)
WARNDEF(  189, 2, FeatureNYI,                     IDS_FeatureNYI2)
ERRORDEF( 190,    ArgsInvalid,                    IDS_ArgsInvalid)
ERRORDEF( 191,    AssgReadonly,                   IDS_AssgReadonly)
ERRORDEF( 192,    RefReadonly,                    IDS_RefReadonly)
ERRORDEF( 193,    PtrExpected,                    IDS_PtrExpected)

ERRORDEF( 196,    PtrIndexSingle,                 IDS_PtrIndexSingle)
WARNDEF(  197, 1, ByRefNonAgileField,             IDS_ByRefNonAgileField)
ERRORDEF( 198,    AssgReadonlyStatic,             IDS_AssgReadonlyStatic)
ERRORDEF( 199,    RefReadonlyStatic,              IDS_RefReadonlyStatic)
ERRORDEF( 200,    AssgReadonlyProp,               IDS_AssgReadonlyProp)
ERRORDEF( 201,    IllegalStatement,               IDS_IllegalStatement)
ERRORDEF( 202,    BadGetEnumerator,               IDS_BadGetEnumerator)
//ERRORDEF( 203,    BadMethodObject,                IDS_BadMethodObject)
ERRORDEF( 204,    TooManyLocals,                  IDS_TooManyLocals)
ERRORDEF( 205,    AbstractBaseCall,               IDS_AbstractBaseCall)
ERRORDEF( 206,    RefProperty,                    IDS_RefProperty)
OLDWARN(  207,    UnsafeProp)
ERRORDEF( 208,    ManagedAddr,                    IDS_ManagedAddr)
ERRORDEF( 209,    BadFixedInitType,               IDS_BadFixedInitType)
ERRORDEF( 210,    FixedMustInit,                  IDS_FixedMustInit)
ERRORDEF( 211,    InvalidAddrOp,                  IDS_InvalidAddrOp)
ERRORDEF( 212,    FixedNeeded,                    IDS_FixedNeeded)
ERRORDEF( 213,    FixedNotNeeded,                 IDS_FixedNotNeeded)
ERRORDEF( 214,    UnsafeNeeded,                   IDS_UnsafeNeeded)
ERRORDEF( 215,    OpTFRetType,                    IDS_OpTFRetType)
ERRORDEF( 216,    OperatorNeedsMatch,             IDS_OperatorNeedsMatch)
ERRORDEF( 217,    BadBoolOp,                      IDS_BadBoolOp)
ERRORDEF( 218,    MustHaveOpTF,                   IDS_MustHaveOpTF)
WARNDEF(  219, 3, UnreferencedVarAssg,            IDS_UnreferencedVarAssg)
ERRORDEF( 220,    CheckedOverflow,                IDS_CheckedOverflow)
ERRORDEF( 221,    ConstOutOfRangeChecked,         IDS_ConstOutOfRangeChecked)
//ERRORDEF( 222,    UnknownRankAddress,             IDS_UnknownRankAddress)
//ERRORDEF( 223,    NoNullCase,                     IDS_NoNullCase)
ERRORDEF( 224,    BadVarargs,                     IDS_BadVarargs)
ERRORDEF( 225,    ParamsMustBeArray,              IDS_ParamsMustBeArray)
ERRORDEF( 226,    IllegalArglist,                 IDS_IllegalArglist)
ERRORDEF( 227,    IllegalUnsafe,                  IDS_IllegalUnsafe)
ERRORDEF( 228,    NoAccessibleMember,             IDS_NoAccessibleMember)
ERRORDEF( 229,    AmbigMember,                    IDS_AmbigMember)
ERRORDEF( 230,    BadForeachDecl,                 IDS_BadForeachDecl)
ERRORDEF( 231,    ParamsLast,                     IDS_ParamsLast)
//ERRORDEF( 232,    AmbigArrayIndex,                IDS_AmbigArrayIndex)
ERRORDEF( 233,    SizeofUnsafe,                   IDS_SizeofUnsafe)
ERRORDEF( 234,    DottedTypeNameNotFoundInNS,     IDS_DottedTypeNameNotFoundInNS)
//ERRORDEF( 235,    VarargDelegate,                 IDS_VarargDelegate)
ERRORDEF( 236,    FieldInitRefNonstatic,          IDS_FieldInitRefNonstatic)
//ERRORDEF( 237,    VarargIndexer,                  IDS_VarargIndexer)
ERRORDEF( 238,    SealedNonOverride,              IDS_SealedNonOverride)
ERRORDEF( 239,    CantOverrideSealed,             IDS_CantOverrideSealed)
ERRORDEF( 241,    NoDefaultArgs,                  IDS_NoDefaultArgs)
ERRORDEF( 242,    VoidError,                      IDS_VoidError)
ERRORDEF( 243,    ConditionalOnOverride,          IDS_ConditionalOnOverride)
ERRORDEF( 244,    PointerInAsOrIs,                IDS_PointerInAsOrIs)
ERRORDEF( 245,    CallingFinalizeDepracated,      IDS_CallingFinalizeDepracated)
ERRORDEF( 246,    SingleTypeNameNotFound,         IDS_SingleTypeNameNotFound)
ERRORDEF( 247,    NegativeStackAllocSize,         IDS_NegativeStackAllocSize)
ERRORDEF( 248,    NegativeArraySize,              IDS_NegativeArraySize)
ERRORDEF( 249,    OverrideFinalizeDeprecated,     IDS_OverrideFinalizeDeprecated)
ERRORDEF( 250,    CallingBaseFinalizeDeprecated,  IDS_CallingBaseFinalizeDeprecated)
WARNDEF(  251, 2, NegativeArrayIndex,             IDS_NegativeArrayIndex)
WARNDEF(  252, 2, BadRefCompareLeft,              IDS_BadRefCompareLeft)
WARNDEF(  253, 2, BadRefCompareRight,             IDS_BadRefCompareRight)
ERRORDEF( 254,    BadCastInFixed,                 IDS_BadCastInFixed)
ERRORDEF( 255,    StackallocInCatchFinally,       IDS_StackallocInCatchFinally)
ERRORDEF( 257,    VarargsLast,                    IDS_VarargsLast)
ERRORDEF( 260,    MissingPartial,                 IDS_MissingPartial)
ERRORDEF( 261,    PartialTypeKindConflict,        IDS_PartialTypeKindConflict)
ERRORDEF( 262,    PartialModifierConflict,        IDS_PartialModifierConflict)
ERRORDEF( 263,    PartialMultipleBases,           IDS_PartialMultipleBases)
ERRORDEF( 264,    PartialWrongTypeParams,         IDS_PartialWrongTypeParams)
ERRORDEF( 265,    PartialWrongConstraints,        IDS_PartialWrongConstraints)
ERRORDEF( 266,    NoImplicitConvCast,             IDS_NoImplicitConvCast) 
ERRORDEF( 267,    PartialMisplaced,               IDS_PartialMisplaced)
ERRORDEF( 268,    ImportedCircularBase,           IDS_ImportedCircularBase)
ERRORDEF( 269,    UseDefViolationOut,             IDS_UseDefViolationOut)
ERRORDEF( 270,    ArraySizeInDeclaration,         IDS_ArraySizeInDeclaration)
ERRORDEF( 271,    InaccessibleGetter,             IDS_InaccessibleGetter)
ERRORDEF( 272,    InaccessibleSetter,             IDS_InaccessibleSetter)
ERRORDEF( 273,    InvalidPropertyAccessMod,       IDS_InvalidPropertyAccessMod)
ERRORDEF( 274,    DuplicatePropertyAccessMods,    IDS_DuplicatePropertyAccessMods)
ERRORDEF( 275,    PropertyAccessModInInterface,   IDS_PropertyAccessModInInterface)
ERRORDEF( 276,    AccessModMissingAccessor,       IDS_AccessModMissingAccessor)
ERRORDEF( 277,    UnimplementedInterfaceAccessor, IDS_UnimplementedInterfaceAccessor)
WARNDEF(  278, 2, PatternIsAmbiguous,             IDS_PatternIsAmbiguous)
WARNDEF(  279, 2, PatternStaticOrInaccessible,    IDS_PatternStaticOrInaccessible)
WARNDEF(  280, 2, PatternBadSignature,            IDS_PatternBadSignature)
ERRORDEF( 281,    FriendRefNotEqualToThis,        IDS_FriendRefNotEqualToThis)
WARNDEF(  282, 3, SequentialOnPartialClass,       IDS_SequentialOnPartialClass)
ERRORDEF( 283,    BadConstType,                   IDS_BadConstType)
ERRORDEF( 304,    NoNewTyvar,                     IDS_NoNewTyvar)
ERRORDEF( 305,    BadArity,                       IDS_BadArity)
ERRORDEF( 306,    BadTypeArgument,                IDS_BadTypeArgument)
ERRORDEF( 307,    TypeArgsNotAllowed,             IDS_TypeArgsNotAllowed)
ERRORDEF( 308,    HasNoTypeVars,                  IDS_HasNoTypeVars)
ERRORDEF( 309,    GenericConstraintNotSatisfied,  IDS_GenericConstraintNotSatisfied)
ERRORDEF( 310,    NewConstraintNotSatisfied,      IDS_NewConstraintNotSatisfied)

ERRORDEF( 400,    GlobalSingleTypeNameNotFound,   IDS_GlobalSingleTypeNameNotFound)
ERRORDEF( 401,    NewBoundMustBeLast,             IDS_NewBoundMustBeLast)
WARNDEF(  402, 4, MainCantBeGeneric,              IDS_MainCantBeGeneric)
ERRORDEF( 403,    TypeVarCantBeNull,              IDS_TypeVarCantBeNull)
ERRORDEF( 404,    AttributeCantBeGeneric,         IDS_AttributeCantBeGeneric)
ERRORDEF( 405,    DuplicateBound,                 IDS_DuplicateBound)
ERRORDEF( 406,    ClassBoundNotFirst,             IDS_ClassBoundNotFirst)
ERRORDEF( 407,    BadRetType,                     IDS_BadRetType)
//ERRORDEF( 408,    OverloadUnified,                IDS_OverloadUnified)
ERRORDEF( 409,    DuplicateConstraintClause,      IDS_DuplicateConstraintClause)
ERRORDEF( 410,    WrongSignature,                 IDS_WrongSignature)
ERRORDEF( 411,    CantInferMethTypeArgs,          IDS_CantInferMethTypeArgs)
ERRORDEF( 412,    LocalSameNameAsTypeParam,       IDS_LocalSameNameAsTypeParam)
ERRORDEF( 413,    AsWithTypeVar,                  IDS_AsWithTypeVar)
WARNDEF(  414, 3, UnreferencedFieldAssg,          IDS_UnreferencedFieldAssg)
ERRORDEF( 415,    BadIndexerNameAttr,             IDS_BadIndexerNameAttr)
ERRORDEF( 416,    AttrArgWithTypeVars,            IDS_AttrArgWithTypeVars)
ERRORDEF( 417,    NewTyvarWithArgs,               IDS_NewTyvarWithArgs)
ERRORDEF( 418,    AbstractSealedStatic,           IDS_AbstractSealedStatic)
WARNDEF(  419, 3, AmbiguousXMLReference,          IDS_AmbiguousXMLReference)
WARNDEF(  420, 1, VolatileByRef,                  IDS_VolatileByRef)
//ERRORDEF( 421,    IllegalParams,                  IDS_IllegalParams)
WARNDEF(  422, 4, IncrSwitchObsolete,             IDS_IncrSwitchObsolete)
ERRORDEF( 423,    ComImportWithImpl,              IDS_ComImportWithImpl)
ERRORDEF( 424,    ComImportWithBase,              IDS_ComImportWithBase)
ERRORDEF( 425,    ImplBadConstraints,             IDS_ImplBadConstraints)
ERRORDEF( 426,    DottedTypeNameNotFoundInAgg,    IDS_DottedTypeNameNotFoundInAgg)
ERRORDEF( 428,    MethGrpToNonDel,                IDS_MethGrpToNonDel)
WARNDEF(  429, 4, UnreachableExpr,                IDS_UnreachableExpr)
ERRORDEF( 430,    BadExternAlias,                 IDS_BadExternAlias)
ERRORDEF( 431,    ColColWithTypeAlias,            IDS_ColColWithTypeAlias)
ERRORDEF( 432,    AliasNotFound,                  IDS_AliasNotFound)
ERRORDEF( 433,    SameFullNameAggAgg,             IDS_SameFullNameAggAgg)
ERRORDEF( 434,    SameFullNameNsAgg,              IDS_SameFullNameNsAgg)
WARNDEF(  435, 2, SameFullNameThisNsAgg,          IDS_SameFullNameThisNsAgg)
WARNDEF(  436, 2, SameFullNameThisAggAgg,         IDS_SameFullNameThisAggAgg)
WARNDEF(  437, 2, SameFullNameThisAggNs,          IDS_SameFullNameThisAggNs)
ERRORDEF( 438,    SameFullNameThisAggThisNs,      IDS_SameFullNameThisAggThisNs)
ERRORDEF( 439,    ExternAfterElements,            IDS_ExternAfterElements)
WARNDEF(  440, 2, GlobalAliasDefn,                IDS_GlobalAliasDefn)
ERRORDEF( 441,    SealedStaticClass,              IDS_SealedStaticClass)
ERRORDEF( 442,    PrivateAbstractAccessor,        IDS_PrivateAbstractAccessor)
ERRORDEF( 443,    ValueExpected,                  IDS_ValueExpected)
WARNDEF(  444, 2, UnexpectedPredefTypeLoc,        IDS_UnexpectedPredefTypeLoc)
ERRORDEF( 445,    UnboxNotLValue,                 IDS_UnboxNotLValue)
ERRORDEF( 446,    AnonMethGrpInForEach,           IDS_AnonMethGrpInForEach)
ERRORDEF( 447,    AttrOnTypeArg,                  IDS_AttrOnTypeArg)
ERRORDEF( 448,    BadIncDecRetType,               IDS_BadIncDecRetType)
ERRORDEF( 449,    RefValBoundMustBeFirst,         IDS_RefValBoundMustBeFirst)
ERRORDEF( 450,    RefValBoundWithClass,           IDS_RefValBoundWithClass)
ERRORDEF( 451,    NewBoundWithVal,                IDS_NewBoundWithVal)
ERRORDEF( 452,    RefConstraintNotSatisfied,      IDS_RefConstraintNotSatisfied)
ERRORDEF( 453,    ValConstraintNotSatisfied,      IDS_ValConstraintNotSatisfied)
ERRORDEF( 454,    CircularConstraint,             IDS_CircularConstraint)
ERRORDEF( 455,    BaseConstraintConflict,         IDS_BaseConstraintConflict)
ERRORDEF( 456,    ConWithValCon,                  IDS_ConWithValCon)
ERRORDEF( 457,    AmbigUDConv,                    IDS_AmbigUDConv)
WARNDEF(  458, 2, AlwaysNull,                     IDS_AlwaysNull)
ERRORDEF( 459,    AddrOnReadOnlyLocal,            IDS_AddrOnReadOnlyLocal)
ERRORDEF( 460,    OverrideWithConstraints,        IDS_OverrideWithConstraints)
//WARNDEF(  461, 1, NullableNeedsValType,           IDS_NullableNeedsValType)
ERRORDEF( 462,    AmbigOverride,                  IDS_AmbigOverride)
ERRORDEF( 463,    DecConstError,                  IDS_DecConstError)
WARNDEF(  464, 2, CmpAlwaysFalse,                 IDS_CmpAlwaysFalse)
WARNDEF(  465, 1, FinalizeMethod,                 IDS_FinalizeMethod)
ERRORDEF( 466,    ExplicitImplParams,             IDS_ExplicitImplParams)
WARNDEF(  467, 2, AmbigLookupMeth,                IDS_AmbigLookupMeth)
ERRORDEF( 468,    SameFullNameThisAggThisAgg,     IDS_SameFullNameThisAggThisAgg)
WARNDEF(  469, 2, GotoCaseShouldConvert,          IDS_GotoCaseShouldConvert)
ERRORDEF( 470,    MethodImplementingAccessor,     IDS_MethodImplementingAccessor)
ERRORDEF( 471,    TypeArgsNotAllowedAmbig,        IDS_TypeArgsNotAllowedAmbig)
WARNDEF(  472, 2, NubExprIsConstBool,             IDS_NubExprIsConstBool)

ERRORDEF( 500,    AbstractHasBody,                IDS_AbstractHasBody)
ERRORDEF( 501,    ConcreteMissingBody,            IDS_ConcreteMissingBody)
ERRORDEF( 502,    AbstractAndSealed,              IDS_AbstractAndSealed)
ERRORDEF( 503,    AbstractNotVirtual,             IDS_AbstractNotVirtual)
ERRORDEF( 504,    StaticConstant,                 IDS_StaticConstant)
ERRORDEF( 505,    CantOverrideNonFunction,        IDS_CantOverrideNonFunction)
ERRORDEF( 506,    CantOverrideNonVirtual,         IDS_CantOverrideNonVirtual)
ERRORDEF( 507,    CantChangeAccessOnOverride,     IDS_CantChangeAccessOnOverride)
ERRORDEF( 508,    CantChangeReturnTypeOnOverride, IDS_CantChangeReturnTypeOnOverride)
ERRORDEF( 509,    CantDeriveFromSealedType,       IDS_CantDeriveFromSealedType)
//ERRORDEF( 510,    RelatedSymbolError,             IDS_RelatedSymbolError)
//WARNDEF(  511, 4, RelatedSymbolWarning,           IDS_RelatedSymbolWarning)
// Error 512 not used
ERRORDEF( 513,    AbstractInConcreteClass,        IDS_AbstractInConcreteClass)
ERRORDEF( 514,    StaticConstructorWithExplicitConstructorCall,
                                                  IDS_StaticConstructorWithExplicitConstructorCall)
ERRORDEF( 515,    StaticConstructorWithAccessModifiers,
                                                  IDS_StaticConstructorWithAccessModifiers)
ERRORDEF( 516,    RecursiveConstructorCall,       IDS_RecursiveConstructorCall)
ERRORDEF( 517,    ObjectCallingBaseConstructor,   IDS_ObjectCallingBaseConstructor)
ERRORDEF( 518,    PredefinedTypeNotFound,         IDS_PredefinedTypeNotFound)
// ERRORDEF( 519,    PredefinedTypeBadNamespace,     IDS_PredefinedTypeBadNamespace)
ERRORDEF( 520,    PredefinedTypeBadType,          IDS_PredefinedTypeBadType)
// Error 521 not used
ERRORDEF( 522,    StructWithBaseConstructorCall,  IDS_StructWithBaseConstructorCall)
ERRORDEF( 523,    StructLayoutCycle,              IDS_StructLayoutCycle)
ERRORDEF( 524,    InterfacesCannotContainTypes,   IDS_InterfacesCannotContainTypes)
ERRORDEF( 525,    InterfacesCantContainFields,    IDS_InterfacesCantContainFields)
ERRORDEF( 526,    InterfacesCantContainConstructors, IDS_InterfacesCantContainConstructors)
ERRORDEF( 527,    NonInterfaceInInterfaceList,    IDS_NonInterfaceInInterfaceList)
ERRORDEF( 528,    DuplicateInterfaceInBaseList,   IDS_DuplicateInterfaceInBaseList)
ERRORDEF( 529,    CycleInInterfaceInheritance,    IDS_CycleInInterfaceInheritance)
// ERRORDEF( 530,    InterfaceMemberCantHideInheritedMember,        IDS_InterfaceMemberCantHideInheritedMember)
ERRORDEF( 531,    InterfaceMemberHasBody,         IDS_InterfaceMemberHasBody)
// ERRORDEF( 532,    ConflictBetweenInheritedInterfaceMembers,      IDS_ConflictBetweenInheritedInterfaceMembers)
ERRORDEF( 533,    HidingAbstractMethod,           IDS_HidingAbstractMethod)
ERRORDEF( 534,    UnimplementedAbstractMethod,    IDS_UnimplementedAbstractMethod)
ERRORDEF( 535,    UnimplementedInterfaceMember,   IDS_UnimplementedInterfaceMember)
ERRORDEF( 536,    CloseUnimplementedInterfaceMember,             IDS_CloseUnimplementedInterfaceMember)
ERRORDEF( 537,    ObjectCantHaveBases,            IDS_ObjectCantHaveBases)
ERRORDEF( 538,    ExplicitInterfaceImplementationNotInterface,   IDS_ExplicitInterfaceImplementationNotInterface)
ERRORDEF( 539,    InterfaceMemberNotFound,        IDS_InterfaceMemberNotFound)
ERRORDEF( 540,    ClassDoesntImplementInterface,  IDS_ClassDoesntImplementInterface)
ERRORDEF( 541,    ExplicitInterfaceImplementationInNonClassOrStruct, IDS_ExplicitInterfaceImplementationInNonClassOrStruct)
ERRORDEF( 542,    MemberNameSameAsType,           IDS_MemberNameSameAsType)
ERRORDEF( 543,    EnumeratorOverflow,             IDS_EnumeratorOverflow)
ERRORDEF( 544,    CantOverrideNonProperty,        IDS_CantOverrideNonProperty)
ERRORDEF( 545,    NoGetToOverride,                IDS_NoGetToOverride)
ERRORDEF( 546,    NoSetToOverride,                IDS_NoSetToOverride)
ERRORDEF( 547,    PropertyCantHaveVoidType,       IDS_PropertyCantHaveVoidType)
ERRORDEF( 548,    PropertyWithNoAccessors,        IDS_PropertyWithNoAccessors)
ERRORDEF( 549,    NewVirtualInSealed,             IDS_NewVirtualInSealed)
ERRORDEF( 550,    ExplicitPropertyAddingAccessor, IDS_ExplicitPropertyAddingAccessor)
ERRORDEF( 551,    ExplicitPropertyMissingAccessor,IDS_ExplicitPropertyMissingAccessor)
ERRORDEF( 552,    ConversionWithInterface,        IDS_ConversionWithInterface)
ERRORDEF( 553,    ConversionWithBase,             IDS_ConversionWithBase)
ERRORDEF( 554,    ConversionWithDerived,          IDS_ConversionWithDerived)
ERRORDEF( 555,    IdentityConversion,             IDS_IdentityConversion)
ERRORDEF( 556,    ConversionNotInvolvingContainedType, IDS_ConversionNotInvolvingContainedType)
ERRORDEF( 557,    DuplicateConversionInClass,     IDS_DuplicateConversionInClass)
ERRORDEF( 558,    OperatorsMustBeStatic,          IDS_OperatorsMustBeStatic)
ERRORDEF( 559,    BadIncDecSignature,             IDS_BadIncDecSignature)
//ERRORDEF( 560,    CantOverrideAccessor,           IDS_CantOverrideAccessor)
//ERRORDEF( 561,    CantOverrideSpecialMethod,      IDS_CantOverrideSpecialMethod)
ERRORDEF( 562,    BadUnaryOperatorSignature,      IDS_BadUnaryOperatorSignature)
ERRORDEF( 563,    BadBinaryOperatorSignature,     IDS_BadBinaryOperatorSignature)
ERRORDEF( 564,    BadShiftOperatorSignature,      IDS_BadShiftOperatorSignature)
//ERRORDEF( 565,    BadEqualsOperatorSignature,     IDS_BadEqualsOperatorSignature)
//ERRORDEF( 566,    BadCompareOperatorSignature,    IDS_BadCompareOperatorSignature)
ERRORDEF( 567,    InterfacesCantContainOperators, IDS_InterfacesCantContainOperators)
ERRORDEF( 568,    StructsCantContainDefaultContructor, IDS_StructsCantContainDefaultContructor)
ERRORDEF( 569,    CantOverrideBogusMethod,        IDS_CantOverrideBogusMethod)
ERRORDEF( 570,    BindToBogus,                    IDS_BindToBogus)
ERRORDEF( 571,    CantCallSpecialMethod,          IDS_CantCallSpecialMethod)
ERRORDEF( 572,    BadTypeReference,               IDS_BadTypeReference)
ERRORDEF( 573,    FieldInitializerInStruct,       IDS_FieldInitializerInStruct)
ERRORDEF( 574,    BadDestructorName,              IDS_BadDestructorName)
ERRORDEF( 575,    OnlyClassesCanContainDestructors,    IDS_OnlyClassesCanContainDestructors)
ERRORDEF( 576,    ConflictAliasAndMember,         IDS_ConflictAliasAndMember)
ERRORDEF( 577,    ConditionalOnSpecialMethod,     IDS_ConditionalOnSpecialMethod)
ERRORDEF( 578,    ConditionalMustReturnVoid,      IDS_ConditionalMustReturnVoid)
ERRORDEF( 579,    DuplicateAttribute,             IDS_DuplicateAttribute)
//ERRORDEF( 580,    TooManyArgumentsToAttribute,    IDS_TooManyArgumentsToAttribute)
//ERRORDEF( 581,    NamedArgumentToAttribute,       IDS_NamedArgumentToAttribute)
ERRORDEF( 582,    ConditionalOnInterfaceMethod,   IDS_ConditionalOnInterfaceMethod)
ERRORDEF( 583,    ICE_Culprit,                    IDS_ICE_Culprit)
ERRORDEF( 584,    ICE_Symbol,                     IDS_ICE_Symbol)
ERRORDEF( 585,    ICE_Node,                       IDS_ICE_Node)
ERRORDEF( 586,    ICE_File,                       IDS_ICE_File)
ERRORDEF( 587,    ICE_Stage,                      IDS_ICE_Stage)
ERRORDEF( 588,    ICE_Lexer,                      IDS_ICE_Lexer)
ERRORDEF( 589,    ICE_Parser,                     IDS_ICE_Parser)
ERRORDEF( 590,    OperatorCantReturnVoid,         IDS_OperatorCantReturnVoid)
ERRORDEF( 591,    InvalidAttributeArgument,       IDS_InvalidAttributeArgument)
ERRORDEF( 592,    AttributeOnBadSymbolType,       IDS_AttributeOnBadSymbolType)
//ERRORDEF( 593,    DualWithoutUuidAttribute,       IDS_DualWithoutUuidAttribute)
ERRORDEF( 594,    FloatOverflow,                  IDS_FloatOverflow)
//ERRORDEF( 595,    ComImportOnNonEmptyClass,       IDS_ComImportOnNonEmptyClass)
ERRORDEF( 596,    ComImportWithoutUuidAttribute,  IDS_ComImportWithoutUuidAttribute)
//ERRORDEF( 597,    TooFewArgumentsToAttribute,     IDS_TooFewArgumentsToAttribute)
//ERRORDEF( 598,    InvalidGuidArgument,            IDS_InvalidGuidArgument)
ERRORDEF( 599,    InvalidNamedArgument,           IDS_InvalidNamedArgument)
//ERRORDEF( 600,    DuplicateAttributeArgument,     IDS_DuplicateAttributeArgument)
ERRORDEF( 601,    DllImportOnInvalidMethod,       IDS_DllImportOnInvalidMethod)
WARNDEF( 602, 1,  FeatureDeprecated,              IDS_FeatureDeprecated)
//ERRORDEF( 603,    AttributeClassNotPublic,        IDS_AttributeClassNotPublic)
//ERRORDEF( 604,    AttributeClassInNonPublic,      IDS_AttributeClassInNonPublic)
//ERRORDEF( 605,    AttributeConstructorWithBadArgument, IDS_AttributeConstructorWithBadArgument)
//ERRORDEF( 606,    AttributeFieldWithBadType,      IDS_AttributeFieldWithBadType)
//ERRORDEF( 607,    AttributeClassMustHaveConstructor,     IDS_AttributeClassMustHaveConstructor)
//ERRORDEF( 608,    MethodSysNativeAndDllImport,    IDS_MethodSysNativeAndDllImport)
ERRORDEF( 609,    NameAttributeOnOverride,        IDS_NameAttributeOnOverride)
ERRORDEF( 610,    FieldCantBeRefAny,              IDS_FieldCantBeRefAny)
ERRORDEF( 611,    ArrayElementCantBeRefAny,       IDS_ArrayElementCantBeRefAny)
WARNDEF(  612, 1, DeprecatedSymbol,               IDS_DeprecatedSymbol)
//WARNDEF(613, 1,    InternalAccessBug,              IDS_InternalAccessBug)
//ERRORDEF( 614,    ConversionWithVariant,          IDS_ConversionWithVariant)
//ERRORDEF( 615,    CantOverrideFinal,              IDS_CantOverrideFinal)
ERRORDEF( 616,    NotAnAttributeClass,            IDS_NotAnAttributeClass)
ERRORDEF( 617,    BadNamedAttributeArgument,      IDS_BadNamedAttributeArgument)
WARNDEF(  618, 2, DeprecatedSymbolStr,            IDS_DeprecatedSymbolStr)
ERRORDEF( 619,    DeprecatedSymbolStr,            IDS_DeprecatedSymbolStr)  // intentionally the same message as 618
ERRORDEF( 620,    IndexerCantHaveVoidType,        IDS_IndexerCantHaveVoidType)
ERRORDEF( 621,    VirtualPrivate,                 IDS_VirtualPrivate)
ERRORDEF( 622,    ArrayInitToNonArrayType,        IDS_ArrayInitToNonArrayType)
ERRORDEF( 623,    ArrayInitInBadPlace,            IDS_ArrayInitInBadPlace)
//ERRORDEF( 624,    ReturnsHResultOnBadMethod,      IDS_ReturnsHResultOnBadMethod)
ERRORDEF( 625,    MissingStructOffset,            IDS_MissingStructOffset)
WARNDEF(  626, 1, ExternMethodNoImplementation,   IDS_ExternMethodNoImplementation)
//ERRORDEF( 627,    SysNativeOnNonExternal,         IDS_SysNativeOnNonExternal)
WARNDEF(  628, 4, ProtectedInSealed,              IDS_ProtectedInSealed)
ERRORDEF( 629,    InterfaceImplementedByConditional, IDS_InterfaceImplementedByConditional)
//ERRORDEF( 630,    UnionContainsRef,               IDS_UnionContainsRef)
ERRORDEF( 631,    IllegalRefParam,                IDS_IllegalRefParam)
//ERRORDEF( 632,    NamedAttrArgIsReadOnlyProperty, IDS_NamedAttrArgIsReadOnlyProperty)
ERRORDEF( 633,    BadArgumentToAttribute,         IDS_BadArgumentToAttribute)
ERRORDEF( 634,    OnlyValidOnCustomMarshaller,    IDS_OnlyValidOnCustomMarshaller)
ERRORDEF( 635,    MissingComTypeOrMarshaller,     IDS_MissingComTypeOrMarshaller)
ERRORDEF( 636,    StructOffsetOnBadStruct,        IDS_StructOffsetOnBadStruct)
ERRORDEF( 637,    StructOffsetOnBadField,         IDS_StructOffsetOnBadField)
//ERRORDEF( 638,    UnknownGlobalAttribute,         IDS_UnknownGlobalAttribute)
//ERRORDEF( 639,    DuplicateGlobalAttribute,       IDS_DuplicateGlobalAttribute)
//ERRORDEF( 640,    AssemblyAttributeOnNonAssembly, IDS_AssemblyAttributeOnNonAssembly)
ERRORDEF( 641,    AttributeUsageOnNonAttributeClass,
                                                  IDS_AttributeUsageOnNonAttributeClass)
WARNDEF(  642, 3, PossibleMistakenNullStatement,  IDS_PossibleMistakenNullStatement)
ERRORDEF( 643,    DuplicateNamedAttributeArgument,IDS_DuplicateNamedAttributeArgument)
ERRORDEF( 644,    DeriveFromEnumOrValueType,      IDS_DeriveFromEnumOrValueType)
ERRORDEF( 645,    IdentifierTooLong,              IDS_IdentifierTooLong)
ERRORDEF( 646,    DefaultMemberOnIndexedType,     IDS_DefaultMemberOnIndexedType)
ERRORDEF( 647,    CustomAttributeError,           IDS_CustomAttributeError)
ERRORDEF( 648,    BogusType,                      IDS_BogusType)
WARNDEF(  649, 4, UnassignedInternalField,        IDS_UnassignedInternalField)
ERRORDEF( 650,    CStyleArray,                    IDS_CStyleArray)
WARNDEF(  652, 2, VacuousIntegralComp,            IDS_VacuousIntegralComp)
ERRORDEF( 653,    AbstractAttributeClass,         IDS_AbstractAttributeClass)
//ERRORDEF( 654,    BadUseOfMethod,                 IDS_BadUseOfMethod)
ERRORDEF( 655,    BadNamedAttributeArgumentType,  IDS_BadNamedAttributeArgumentType)
ERRORDEF( 656,    MissingPredefinedMember,        IDS_MissingPredefinedMember)
WARNDEF(  657, 1, AttributeLocationOnBadDeclaration,
                                                  IDS_AttributeLocationOnBadDeclaration)
WARNDEF(  658, 1, InvalidAttributeLocation,       IDS_InvalidAttributeLocation)
WARNDEF(  659, 3, EqualsWithoutGetHashCode,       IDS_EqualsWithoutGetHashCode)
WARNDEF(  660, 3, EqualityOpWithoutEquals,        IDS_EqualityOpWithoutEquals)
WARNDEF(  661, 3, EqualityOpWithoutGetHashCode,   IDS_EqualityOpWithoutGetHashCode)
ERRORDEF( 662,    OutAttrOnRefParam,              IDS_OutAttrOnRefParam)
ERRORDEF( 663,    OverloadRefOut,                 IDS_OverloadRefOut)
ERRORDEF( 664,    LiteralDoubleCast,              IDS_LiteralDoubleCast)
WARNDEF(  665, 3, IncorrectBooleanAssg,           IDS_IncorrectBooleanAssg)
ERRORDEF( 666,    ProtectedInStruct,              IDS_ProtectedInStruct)
ERRORDEF( 667,    FeatureDeprecated,              IDS_FeatureDeprecated)
ERRORDEF( 668,    InconsistantIndexerNames,       IDS_InconsistantIndexerNames)
ERRORDEF( 669,    ComImportWithUserCtor,          IDS_ComImportWithUserCtor)
ERRORDEF( 670,    FieldCantHaveVoidType,          IDS_FieldCantHaveVoidType)
//WARNDEF(  671, 2, IDisposableAndIEnumerator,      IDS_IDisposableAndIEnumerator)
WARNDEF(  672, 1, NonObsoleteOverridingObsolete,  IDS_NonObsoleteOverridingObsolete)
ERRORDEF( 673,    SystemVoid,                     IDS_SystemVoid)
ERRORDEF( 674,    ExplicitParamArray,             IDS_ExplicitParamArray)
WARNDEF(  675, 3, BitwiseOrSignExtend,            IDS_BitwiseOrSignExtend)
//ERRORDEF( 676,    VolatileByRef,                  IDS_VolatileByRef) Changed to warning #420
ERRORDEF( 677,    VolatileStruct,                 IDS_VolatileStruct)
ERRORDEF( 678,    VolatileAndReadonly,            IDS_VolatileAndReadonly)
OLDWARN(  679,    ProtectedInternal)    // Not Used
OLDWARN(  680,    AccessibleReadonly)
ERRORDEF( 681,    AbstractField,                  IDS_AbstractField)
ERRORDEF( 682,    BogusExplicitImpl,              IDS_BogusExplicitImpl)
ERRORDEF( 683,    ExplicitMethodImplAccessor,     IDS_ExplicitMethodImplAccessor)
WARNDEF(  684, 1, CoClassWithoutComImport,        IDS_CoClassWithoutComImport)
ERRORDEF( 685,    ConditionalWithOutParam,        IDS_ConditionalWithOutParam)
ERRORDEF( 686,    AccessorImplementingMethod,     IDS_AccessorImplementingMethod)
ERRORDEF( 687,    AliasQualAsExpression,          IDS_AliasQualAsExpression)
WARNDEF(  688, 1, LinkDemandOnOverride,           IDS_LinkDemandOnOverride)
ERRORDEF( 689,    DerivingFromATyVar,             IDS_DerivingFromATyVar)
FATALDEF( 690,    MalformedMetadata,              IDS_MalformedMetadata)
ERRORDEF( 692,    DuplicateTypeParameter,         IDS_DuplicateTypeParameter)
WARNDEF(  693, 3, TypeParameterSameAsOuterTypeParameter,
                                                  IDS_TypeParameterSameAsOuterTypeParameter)
ERRORDEF( 694,    TypeVariableSameAsParent,       IDS_TypeVariableSameAsParent)
ERRORDEF( 695,    UnifyingInterfaceInstantiations,IDS_UnifyingInterfaceInstantiations)
// ERRORDEF( 696,    ExternOnGeneric,                IDS_ExternOnGeneric)
// ERRORDEF( 697,    ExternOnGenericMethod,          IDS_ExternOnGenericMethod)
ERRORDEF( 698,    GenericDerivingFromAttribute,   IDS_GenericDerivingFromAttribute)
ERRORDEF( 699,    TyVarNotFoundInConstraint,      IDS_TyVarNotFoundInConstraint)
// ERRORDEF( 700,    TyVarAsBound,                   IDS_TyVarAsBound)
ERRORDEF( 701,    BadBoundType,                   IDS_BadBoundType)
ERRORDEF( 702,    SpecialTypeAsBound,             IDS_SpecialTypeAsBound)
ERRORDEF( 703,    BadVisBound,                    IDS_BadVisBound)
ERRORDEF( 704,    LookupInTypeVariable,           IDS_LookupInTypeVariable)

ERRORDEF( 706,    BadConstraintType,              IDS_BadConstraintType)
// ERRORDEF( 707,    ColonColonParseError,           IDS_ColonColonParseError)
ERRORDEF( 708,    InstanceMemberInStaticClass,    IDS_InstanceMemberInStaticClass)
ERRORDEF( 709,    StaticBaseClass,                IDS_StaticBaseClass)
ERRORDEF( 710,    ConstructorInStaticClass,       IDS_ConstructorInStaticClass)
ERRORDEF( 711,    DestructorInStaticClass,        IDS_DestructorInStaticClass)
ERRORDEF( 712,    InstantiatingStaticClass,       IDS_InstantiatingStaticClass)
ERRORDEF( 713,    StaticDerivedFromNonObject,     IDS_StaticDerivedFromNonObject)
ERRORDEF( 714,    StaticClassInterfaceImpl,       IDS_StaticClassInterfaceImpl)
ERRORDEF( 715,    OperatorInStaticClass,          IDS_OperatorInStaticClass)
ERRORDEF( 716,    ConvertToStaticClass,           IDS_ConvertToStaticClass)
ERRORDEF( 717,    ConstraintIsStaticClass,        IDS_ConstraintIsStaticClass)
ERRORDEF( 718,    GenericArgIsStaticClass,        IDS_GenericArgIsStaticClass)
ERRORDEF( 719,    ArrayOfStaticClass,             IDS_ArrayOfStaticClass)
ERRORDEF( 720,    IndexerInStaticClass,           IDS_IndexerInStaticClass)
ERRORDEF( 721,    ParameterIsStaticClass,         IDS_ParameterIsStaticClass)
ERRORDEF( 722,    ReturnTypeIsStaticClass,        IDS_ReturnTypeIsStaticClass)
ERRORDEF( 723,    VarDeclIsStaticClass,           IDS_VarDeclIsStaticClass)
ERRORDEF( 724,    BadEmptyThrowInFinally,         IDS_BadEmptyThrowInFinally)
WARNDEF(  728, 2, AssignmentToLockOrDispose,	  IDS_AssignmentToLockOrDispose)
ERRORDEF( 729,    ForwardedTypeInThisAssembly,    IDS_ForwardedTypeInThisAssembly)
ERRORDEF( 730,    ForwardedTypeIsNested,          IDS_ForwardedTypeIsNested)
ERRORDEF( 731,    CycleInTypeForwarder,           IDS_CycleInTypeForwarder)
ERRORDEF( 733,    FwdedGeneric,                   IDS_FwdedGeneric)
ERRORDEF( 734,    AssemblyNameOnNonModule,        IDS_AssemblyNameOnNonModule)
ERRORDEF( 735,    InvalidFwdType,                 IDS_InvalidFwdType)

ERRORDEF(1001,    IdentifierExpected,             IDS_IdentifierExpected)
ERRORDEF(1002,    SemicolonExpected,              IDS_SemicolonExpected)
ERRORDEF(1003,    SyntaxError,                    IDS_SyntaxError)
ERRORDEF(1004,    DuplicateModifier,              IDS_DuplicateModifier)
//ERRORDEF(1005,    IllegalPointerType,             IDS_IllegalPointerType)   // Not Used
//ERRORDEF(1006,    BadConstructorName,             IDS_BadConstructorName)   // Not Used
ERRORDEF(1007,    DuplicateAccessor,              IDS_DuplicateAccessor)
ERRORDEF(1008,    IntegralTypeExpected,           IDS_IntegralTypeExpected)
ERRORDEF(1009,    IllegalEscape,                  IDS_IllegalEscape)
ERRORDEF(1010,    NewlineInConst,                 IDS_NewlineInConst)
ERRORDEF(1011,    EmptyCharConst,                 IDS_EmptyCharConst)
ERRORDEF(1012,    TooManyCharsInConst,            IDS_TooManyCharsInConst)
ERRORDEF(1013,    InvalidNumber,                  IDS_InvalidNumber)
ERRORDEF(1014,    GetOrSetExpected,               IDS_GetOrSetExpected)
ERRORDEF(1015,    ClassTypeExpected,              IDS_ClassTypeExpected)
ERRORDEF(1016,    NamedArgumentExpected,          IDS_NamedArgumentExpected)
ERRORDEF(1017,    TooManyCatches,                 IDS_TooManyCatches)
ERRORDEF(1018,    ThisOrBaseExpected,             IDS_ThisOrBaseExpected)
ERRORDEF(1019,    OvlUnaryOperatorExpected,       IDS_OvlUnaryOperatorExpected)
ERRORDEF(1020,    OvlBinaryOperatorExpected,      IDS_OvlBinaryOperatorExpected)
ERRORDEF(1021,    IntOverflow,                    IDS_IntOverflow)
ERRORDEF(1022,    EOFExpected,                    IDS_EOFExpected)
ERRORDEF(1023,    BadEmbeddedStmt,                IDS_BadEmbeddedStmt)
ERRORDEF(1024,    PPDirectiveExpected,            IDS_PPDirectiveExpected)
ERRORDEF(1025,    EndOfPPLineExpected,            IDS_EndOfPPLineExpected)
ERRORDEF(1026,    CloseParenExpected,             IDS_CloseParenExpected)
ERRORDEF(1027,    EndifDirectiveExpected,         IDS_EndifDirectiveExpected)
ERRORDEF(1028,    UnexpectedDirective,            IDS_UnexpectedDirective)
ERRORDEF(1029,    ErrorDirective,                 IDS_ErrorDirective)
WARNDEF( 1030, 1, WarningDirective,               IDS_WarningDirective)
ERRORDEF(1031,    TypeExpected,                   IDS_TypeExpected)
ERRORDEF(1032,    PPDefFollowsToken,              IDS_PPDefFollowsToken)
ERRORDEF(1033,    TooManyLines,                   IDS_TooManyLines)
ERRORDEF(1034,    LineTooLong,                    IDS_LineTooLong)
ERRORDEF(1035,    OpenEndedComment,               IDS_OpenEndedComment)
ERRORDEF(1036,    ExpectedDotOrParen,             IDS_ExpectedDotOrParen)
ERRORDEF(1037,    OvlOperatorExpected,            IDS_OvlOperatorExpected)
ERRORDEF(1038,    EndRegionDirectiveExpected,     IDS_EndRegionDirectiveExpected)
ERRORDEF(1039,    UnterminatedStringLit,          IDS_UnterminatedStringLit)
ERRORDEF(1040,    BadDirectivePlacement,          IDS_BadDirectivePlacement)
ERRORDEF(1041,    IdentifierExpectedKW,           IDS_IdentifierExpectedKW)
//ERRORDEF(1042,    EscapedKeyword,                 IDS_EscapedKeyword)
ERRORDEF(1043,    SemiOrLBraceExpected,           IDS_SemiOrLBraceExpected)
ERRORDEF(1044,    MultiTypeInDeclaration,         IDS_MultiTypeInDeclaration)
ERRORDEF(1055,    AddOrRemoveExpected,            IDS_AddOrRemoveExpected)
ERRORDEF(1056,    UnexpectedCharacter,            IDS_UnexpectedCharacter)
ERRORDEF(1057,    ProtectedInStatic,              IDS_ProtectedInStatic)
WARNDEF(1058, 1,  UnreachableGeneralCatch,        IDS_UnreachableGeneralCatch)



WARNDEF(1200, 1,  FeatureDeprecated2,             IDS_FeatureDeprecated)
WARNDEF(1201, 1,  FeatureDeprecated3,             IDS_FeatureDeprecated)
WARNDEF(1202, 1,  FeatureDeprecated4,             IDS_FeatureDeprecated)
WARNDEF(1203, 1,  FeatureDeprecated5,             IDS_FeatureDeprecated)
OLDWARN(1204,     FeatureDefaultDeprecated)

ERRORDEF(1501,    BadArgCount,                    IDS_BadArgCount)
ERRORDEF(1502,    BadArgTypes,                    IDS_BadArgTypes)
ERRORDEF(1503,    BadArgType,                     IDS_BadArgType)
ERRORDEF(1504,    NoSourceFile,                   IDS_NoSourceFile)


ERRORDEF(1507,    CantRefResource,                IDS_CantRefResource)
ERRORDEF(1508,    ResourceNotUnique,              IDS_ResourceNotUnique)
ERRORDEF(1509,    ImportNonAssembly,              IDS_ImportNonAssembly)
ERRORDEF(1510,    RefLvalueExpected,              IDS_RefLvalueExpected)
ERRORDEF(1511,    BaseInStaticMeth,               IDS_BaseInStaticMeth)
ERRORDEF(1512,    BaseInBadContext,               IDS_BaseInBadContext)
ERRORDEF(1513,    RbraceExpected,                 IDS_RbraceExpected)
ERRORDEF(1514,    LbraceExpected,                 IDS_LbraceExpected)
ERRORDEF(1515,    InExpected,                     IDS_InExpected)

ERRORDEF(1517,    InvalidPreprocExpr,             IDS_InvalidPreprocExpr)
ERRORDEF(1518,    BadTokenInType,                 IDS_BadTokenInType)
ERRORDEF(1519,    InvalidMemberDecl,              IDS_InvalidMemberDecl)
ERRORDEF(1520,    MemberNeedsType,                IDS_MemberNeedsType)
ERRORDEF(1521,    BadBaseType,                    IDS_BadBaseType)
WARNDEF( 1522, 1, EmptySwitch,                    IDS_EmptySwitch)
//ERRORDEF(1523,    StmtNotInCase,                  IDS_StmtNotInCase)
ERRORDEF(1524,    ExpectedEndTry,                 IDS_ExpectedEndTry)
ERRORDEF(1525,    InvalidExprTerm,                IDS_InvalidExprTerm)
ERRORDEF(1526,    BadNewExpr,                     IDS_BadNewExpr)
ERRORDEF(1527,    NoNamespacePrivate,             IDS_NoNamespacePrivate)
ERRORDEF(1528,    BadVarDecl,                     IDS_BadVarDecl)
ERRORDEF(1529,    UsingAfterElements,             IDS_UsingAfterElements)
ERRORDEF(1530,    NoNewOnNamespaceElement,        IDS_NoNewOnNamespaceElement)

//ERRORDEF(1532,    AccessorMustOverride,           IDS_AccessorMustOverride)
ERRORDEF(1533,    DontUseInvoke,                  IDS_DontUseInvoke)
ERRORDEF(1534,    BadBinOpArgs,                   IDS_BadBinOpArgs)
ERRORDEF(1535,    BadUnOpArgs,                    IDS_BadUnOpArgs)
ERRORDEF(1536,    NoVoidParameter,                IDS_NoVoidParameter)
ERRORDEF(1537,    DuplicateAlias,                 IDS_DuplicateAlias)
//ERRORDEF(1538,    BadTypeReferenceDerived,        IDS_BadTypeReferenceDerived)
//ERRORDEF(1539,    BadBackQuoteChar,               IDS_BadBackQuoteChar)
ERRORDEF(1540,    BadProtectedAccess,             IDS_BadProtectedAccess)
ERRORDEF(1541,    CantIncludeDirectory,           IDS_CantIncludeDirectory)
ERRORDEF(1542,    AddModuleAssembly,              IDS_AddModuleAssembly)
ERRORDEF(1545,    BindToBogusProp2,               IDS_BindToBogusProp2)
ERRORDEF(1546,    BindToBogusProp1,               IDS_BindToBogusProp1)
ERRORDEF(1547,    NoVoidHere,                     IDS_NoVoidHere)
ERRORDEF(1548,    CryptoFailed,                   IDS_CryptoFailed)
ERRORDEF(1549,    CryptoNotFound,                 IDS_CryptoNotFound)

ERRORDEF(1551,    IndexerNeedsParam,              IDS_IndexerNeedsParam)
ERRORDEF(1552,    BadArraySyntax,                 IDS_BadArraySyntax)
ERRORDEF(1553,    BadOperatorSyntax,              IDS_BadOperatorSyntax)
ERRORDEF(1554,    BadOperatorSyntax2,             IDS_BadOperatorSyntax2)
ERRORDEF(1555,    MainClassNotFound,              IDS_MainClassNotFound)
ERRORDEF(1556,    MainClassNotClass,              IDS_MainClassNotClass)
ERRORDEF(1557,    MainClassWrongFile,             IDS_MainClassWrongFile)
ERRORDEF(1558,    NoMainInClass,                  IDS_NoMainInClass)
ERRORDEF(1559,    MainClassIsImport,              IDS_MainClassIsImport)
ERRORDEF(1560,    FileNameTooLong,                IDS_FileNameTooLong)
ERRORDEF(1561,    OutputFileNameTooLong,          IDS_OutputFileNameTooLong)

ERRORDEF(1562,    OutputNeedsName,                IDS_OutputNeedsName)
ERRORDEF(1563,    OutputNeedsInput,               IDS_OutputNeedsInput)

ERRORDEF(1565,    CantHaveWin32ResAndIcon,        IDS_CantHaveWin32ResAndIcon)
ERRORDEF(1566,    CantReadResource,               IDS_CantReadResource)
ERRORDEF(1567,    AutoResGen,                     IDS_AutoResGen)
ERRORDEF(1569,    DocFileGen,                     IDS_DocFileGen)
WARNDEF( 1570, 1, XMLParseError,                  IDS_XMLParseError)
WARNDEF( 1571, 2, DuplicateParamTag,              IDS_DuplicateParamTag)
WARNDEF( 1572, 2, UnmatchedParamTag,              IDS_UnmatchedParamTag)
WARNDEF( 1573, 4, MissingParamTag,                IDS_MissingParamTag)
WARNDEF( 1574, 1, BadXMLRef,                      IDS_BadXMLRef)
ERRORDEF(1575,    BadStackAllocExpr,              IDS_BadStackAllocExpr)
ERRORDEF(1576,    InvalidLineNumber,              IDS_InvalidLineNumber)
ERRORDEF(1577,    ALinkFailed,                    IDS_ALinkFailed)
ERRORDEF(1578,    MissingPPFile,                  IDS_MissingPPFile)
ERRORDEF(1579,    ForEachMissingMember,           IDS_ForEachMissingMember)
WARNDEF( 1580, 1, BadXMLRefParamType,             IDS_BadXMLRefParamType)
WARNDEF( 1581, 1, BadXMLRefReturnType,            IDS_BadXMLRefReturnType)
//ERRORDEF(1582,    ClsWarnAndTrue,                 IDS_ClsWarnAndTrue)
ERRORDEF(1583,    BadWin32Res,                    IDS_BadWin32Res)
WARNDEF( 1584, 1, BadXMLRefSyntax,                IDS_BadXMLRefSyntax)
ERRORDEF(1585,    BadModifierLocation,            IDS_BadModifierLocation)
ERRORDEF(1586,    MissingArraySize,               IDS_MissingArraySize)
WARNDEF( 1587, 2, UnprocessedXMLComment,          IDS_UnprocessedXMLComment)
ERRORDEF(1588,    CantGetCORSystemDir,            IDS_CantGetCORSystemDir)
WARNDEF( 1589, 1, FailedInclude,                  IDS_FailedInclude)
WARNDEF( 1590, 1, InvalidInclude,                 IDS_InvalidInclude)
WARNDEF( 1591, 4, MissingXMLComment,              IDS_MissingXMLComment)
WARNDEF( 1592, 1, XMLParseIncludeError,           IDS_XMLParseIncludeError)
ERRORDEF(1593,    BadDelArgCount,                 IDS_BadDelArgCount)
ERRORDEF(1594,    BadDelArgTypes,                 IDS_BadDelArgTypes)
OLDWARN( 1595,    MultipleTypeDefs)
OLDWARN( 1596,    DocFileGenAndIncr)
ERRORDEF(1597,    UnexpectedSemicolon,            IDS_UnexpectedSemicolon)
WARNDEF( 1598, 1, XMLParserNotFound,              IDS_XMLParserNotFound)
ERRORDEF(1599,    MethodReturnCantBeRefAny,       IDS_MethodReturnCantBeRefAny)
ERRORDEF(1600,    CompileCancelled,               IDS_CompileCancelled)
ERRORDEF(1601,    MethodArgCantBeRefAny,          IDS_MethodArgCantBeRefAny)
//ERRORDEF(1602,    MultipleLocalTypeDefs,          IDS_MultipleLocalTypeDefs)
//ERRORDEF(1603,    UnnamedOutputAndIncr,           IDS_UnnamedOutputAndIncr)
ERRORDEF(1604,    AssgReadonlyLocal,              IDS_AssgReadonlyLocal)
ERRORDEF(1605,    RefReadonlyLocal,               IDS_RefReadonlyLocal)
ERRORDEF(1606,    ALinkCloseFailed,               IDS_ALinkCloseFailed)
WARNDEF( 1607, 1, ALinkWarn,                      IDS_ALinkWarn)
ERRORDEF(1608,    CantUseRequiredAttribute,       IDS_CantUseRequiredAttribute)
ERRORDEF(1609,    NoModifiersOnAccessor,          IDS_NoModifiersOnAccessor)
WARNDEF( 1610, 4, DeleteAutoResFailed,            IDS_DeleteAutoResFailed)
ERRORDEF(1611,    ParamsCantBeRefOut,             IDS_ParamsCantBeRefOut)
ERRORDEF(1612,    ReturnNotLValue,                IDS_ReturnNotLValue)
ERRORDEF(1613,    MissingCoClass,                 IDS_MissingCoClass)
ERRORDEF(1614,    AmbigousAttribute,              IDS_AmbigousAttribute)
ERRORDEF(1615,    BadArgExtraRef,                 IDS_BadArgExtraRef)
WARNDEF( 1616, 1, CmdOptionConflictsSource,       IDS_CmdOptionConflictsSource)
ERRORDEF(1617,    BadCompatMode,                  IDS_BadCompatMode)
ERRORDEF(1618,    DelegateOnConditional,          IDS_DelegateOnConditional)
ERRORDEF(1619,    CantMakeTempFile,               IDS_CantMakeTempFile)
ERRORDEF(1620,    BadArgRef,                      IDS_BadArgRef)
ERRORDEF(1621,    YieldInAnonMeth,                IDS_YieldInAnonMeth)
ERRORDEF(1622,    ReturnInIterator,               IDS_ReturnInIterator)
ERRORDEF(1623,    BadIteratorArgType,             IDS_BadIteratorArgType)
ERRORDEF(1624,    BadIteratorReturn,              IDS_BadIteratorReturn)
ERRORDEF(1625,    BadYieldInFinally,              IDS_BadYieldInFinally)
ERRORDEF(1626,    BadYieldInTryOfCatch,           IDS_BadYieldInTryOfCatch)
ERRORDEF(1627,    EmptyYield,                     IDS_EmptyYield)
ERRORDEF(1628,    AnonDelegateCantUse,            IDS_AnonDelegateCantUse)
ERRORDEF(1629,    IllegalInnerUnsafe,             IDS_IllegalInnerUnsafe)
ERRORDEF(1630,    BadWatsonMode,                  IDS_BadWatsonMode)
ERRORDEF(1631,    BadYieldInCatch,                IDS_BadYieldInCatch)
ERRORDEF(1632,    BadDelegateLeave,               IDS_BadDelegateLeave)
WARNDEF( 1633, 1, IllegalPragma,                  IDS_IllegalPragma)
WARNDEF( 1634, 1, IllegalPPWarning,               IDS_IllegalPPWarning)
WARNDEF( 1635, 1, BadRestoreNumber,               IDS_BadRestoreNumber)
ERRORDEF(1636,    VarargsIterator,                IDS_VarargsIterator)
ERRORDEF(1637,    UnsafeIteratorArgType,          IDS_UnsafeIteratorArgType)
ERRORDEF(1638,    ReservedIdentifier,             IDS_ReservedIdentifier2)
ERRORDEF(1639,    BadCoClassSig,                  IDS_BadCoClassSig)
ERRORDEF(1640,    MultipleIEnumOfT,               IDS_MultipleIEnumOfT)
ERRORDEF(1641,    FixedDimsRequired,              IDS_FixedDimsRequired)
ERRORDEF(1642,    FixedNotInStruct,               IDS_FixedNotInStruct)
ERRORDEF(1643,    AnonymousReturnExpected,        IDS_AnonymousReturnExpected)
ERRORDEF(1644,    NonECMAFeature,                 IDS_NonECMAFeature)
WARNDEF( 1645, 1, NonECMAFeature,                 IDS_NonECMAFeatureOK)
ERRORDEF(1646,    ExpectedVerbatimLiteral,        IDS_ExpectedVerbatimLiteral)
FATALDEF(1647,    StackOverflow,                  IDS_StackOverflow)
ERRORDEF(1648,    AssgReadonly2,                  IDS_AssgReadonly2)
ERRORDEF(1649,    RefReadonly2,                   IDS_RefReadonly2)
ERRORDEF(1650,    AssgReadonlyStatic2,            IDS_AssgReadonlyStatic2)
ERRORDEF(1651,    RefReadonlyStatic2,             IDS_RefReadonlyStatic2)
ERRORDEF(1652,    AssgReadonlyLocal2,             IDS_AssgReadonlyLocal2)
ERRORDEF(1653,    RefReadonlyLocal2,              IDS_RefReadonlyLocal2)
ERRORDEF(1654,    AssgReadonlyLocal2Cause,        IDS_AssgReadonlyLocal2Cause)
ERRORDEF(1655,    RefReadonlyLocal2Cause,         IDS_RefReadonlyLocal2Cause)
ERRORDEF(1656,    AssgReadonlyLocalCause,         IDS_AssgReadonlyLocalCause)
ERRORDEF(1657,    RefReadonlyLocalCause,          IDS_RefReadonlyLocalCause)
WARNDEF( 1658, 1, ErrorOverride,                  IDS_ErrorOverride)
OLDWARN( 1659,    ReservedIdentifier) // Nuked - too annoying
ERRORDEF(1660,    AnonMethToNonDel,               IDS_AnonMethToNonDel)
ERRORDEF(1661,    CantConvAnonMethParams,         IDS_CantConvAnonMethParams)
ERRORDEF(1662,    CantConvAnonMethReturns,        IDS_CantConvAnonMethReturns)
ERRORDEF(1663,    IllegalFixedType,               IDS_IllegalFixedType)
ERRORDEF(1664,    FixedOverflow,                  IDS_FixedOverflow)
ERRORDEF(1665,    InvalidFixedArraySize,          IDS_InvalidFixedArraySize)
ERRORDEF(1666,    FixedBufferNotFixed,            IDS_FixedBufferNotFixed)
ERRORDEF(1667,    AttributeNotOnAccessor,         IDS_AttributeNotOnAccessor)
WARNDEF( 1668, 2, InvalidSearchPathDir,           IDS_InvalidSearchPathDir)
ERRORDEF(1669,    IllegalVarArgs,                 IDS_IllegalVarArgs)
ERRORDEF(1670,    IllegalParams,                  IDS_IllegalParams)
ERRORDEF(1671,    BadModifiersOnNamespace,        IDS_BadModifiersOnNamespace)
ERRORDEF(1672,    BadPlatformType,                IDS_BadPlatformType)
ERRORDEF(1673,    ThisStructNotInAnonMeth,        IDS_ThisStructNotInAnonMeth)
ERRORDEF(1674,    NoConvToIDisp,                  IDS_NoConvToIDisp)
ERRORDEF(1675,    InvalidGenericEnum,             IDS_InvalidGenericEnum)
ERRORDEF(1676,    BadParamRef,                    IDS_BadParamRef)
ERRORDEF(1677,    BadParamExtraRef,               IDS_BadParamExtraRef)
ERRORDEF(1678,    BadParamType,                   IDS_BadParamType)
ERRORDEF(1679,    BadExternIdentifier,            IDS_BadExternIdentifier)
ERRORDEF(1680,    AliasMissingFile,               IDS_AliasMissingFile)
ERRORDEF(1681,    GlobalExternAlias,              IDS_GlobalExternAlias)
WARNDEF( 1682, 1, MissingTypeNested,              IDS_MissingTypeNested)
WARNDEF( 1683, 1, MissingTypeInSource,            IDS_MissingTypeInSource)
WARNDEF( 1684, 1, MissingTypeInAssembly,          IDS_MissingTypeInAssembly)
WARNDEF( 1685, 1, MultiplePredefTypes,            IDS_MultiplePredefTypes)
ERRORDEF(1686,    LocalCantBeFixedAndHoisted,     IDS_LocalCantBeFixedAndHoisted)
WARNDEF( 1687, 1, TooManyLinesForDebugger,        IDS_TooManyLinesForDebugger)
ERRORDEF(1688,    CantConvAnonMethNoParams,       IDS_CantConvAnonMethNoParams)
ERRORDEF(1689,    ConditionalOnNonAttributeClass, IDS_ConditionalOnNonAttributeClass)
WARNDEF( 1690, 1, CallOnNonAgileField,            IDS_CallOnNonAgileField)
WARNDEF( 1691, 1, BadWarningNumber,               IDS_BadWarningNumber)
WARNDEF( 1692, 1, InvalidNumber,                  IDS_InvalidNumber)
//WARNDEF( 1693, 1, NewlineInConst,                 IDS_NewlineInConst)
WARNDEF( 1694, 1, FileNameTooLong,                IDS_FileNameTooLong)
WARNDEF( 1695, 1, IllegalPPChecksum,              IDS_IllegalPPChecksum)
WARNDEF( 1696, 1, EndOfPPLineExpected,            IDS_EndOfPPLineExpected)
WARNDEF( 1697, 1, ConflictingChecksum,            IDS_ConflictingChecksum)
WARNDEF( 1698, 2, AssumedMatchThis,               IDS_AssumedMatchThis)
WARNDEF( 1699, 1, UseSwitchInsteadOfAttribute,    IDS_UseSwitchInsteadOfAttribute)
WARNDEF( 1700, 3, InvalidAssemblyName,            IDS_InvalidAssemblyName)
WARNDEF( 1701, 2, UnifyReferenceMajMin,           IDS_UnifyReferenceMajMin)
WARNDEF( 1702, 3, UnifyReferenceBldRev,           IDS_UnifyReferenceBldRev)
ERRORDEF(1703,    DuplicateImport,                IDS_DuplicateImport)
ERRORDEF(1704,    DuplicateImportSimple,          IDS_DuplicateImportSimple)
ERRORDEF(1705,    AssemblyMatchBadVersion,        IDS_AssemblyMatchBadVersion)
ERRORDEF(1706,    AnonMethNotAllowed,             IDS_AnonMethNotAllowed)
WARNDEF( 1707, 1, DelegateNewMethBind,            IDS_DelegateNewMethBind)
ERRORDEF(1708,    FixedNeedsLvalue,               IDS_FixedNeedsLvalue)
WARNDEF( 1709, 1, EmptyFileName,                  IDS_EmptyFileName)
WARNDEF( 1710, 2, DuplicateTypeParamTag,          IDS_DuplicateTypeParamTag)
WARNDEF( 1711, 2, UnmatchedTypeParamTag,          IDS_UnmatchedTypeParamTag)
WARNDEF( 1712, 4, MissingTypeParamTag,            IDS_MissingTypeParamTag)
FATALDEF(1713,    TypeNameBuilderError,           IDS_TypeNameBuilderError)
ERRORDEF(1714,    ImportBadBase,                  IDS_ImportBadBase)
ERRORDEF(1715,    CantChangeTypeOnOverride,       IDS_CantChangeTypeOnOverride)
ERRORDEF(1716,    DoNotUseFixedBufferAttr,        IDS_DoNotUseFixedBufferAttr)
WARNDEF( 1717, 3, AssignmentToSelf,               IDS_AssignmentToSelf)
WARNDEF( 1718, 3, ComparisonToSelf,               IDS_ComparisonToSelf)
ERRORDEF(1719,    CantOpenWin32Res,               IDS_CantOpenWin32Res)
WARNDEF( 1720, 1, DotOnDefault,                   IDS_DotOnDefault)
ERRORDEF(1721,    NoMultipleInheritance,          IDS_NoMultipleInheritance)
ERRORDEF(1722,    BaseClassMustBeFirst,           IDS_BaseClassMustBeFirst)
WARNDEF( 1723, 1, BadXMLRefTypeVar,               IDS_BadXMLRefTypeVar)
ERRORDEF(1724,    InvalidDefaultCharSetValue,     IDS_InvalidDefaultCharSetValue)
ERRORDEF(1725,    FriendAssemblyBadArgs,          IDS_FriendAssemblyBadArgs)
ERRORDEF(1726,    FriendAssemblySNReq,            IDS_FriendAssemblySNReq)
ERRORDEF(1727,    WatsonSendNotOptedIn,           IDS_WatsonSendNotOptedIn)
ERRORDEF(1728,    DelegateOnNullable,             IDS_DelegateOnNullable)

ERRORDEF(1900,    BadWarningLevel,                IDS_BadWarningLevel)
//ERRORDEF(1901,    NoWarningsAsErrors,             IDS_NoWarningsAsErrors) // No longer reported
ERRORDEF(1902,    BadDebugType,                   IDS_BadDebugType)

ERRORDEF(1903,    UnknownTestSwitch,              IDS_UnknownTestSwitch)
//ERRORDEF(1904,    BadWarningNumber,               IDS_BadWarningNumber)
ERRORDEF(1906,    BadResourceVis,                 IDS_BadResourceVis)
//ERRORDEF(1907,    NewConstraintAttrUsage,         IDS_NewConstraintAttrUsage)
ERRORDEF(1908,    DefaultValueTypeMustMatch,      IDS_DefaultValueTypeMustMatch)
ERRORDEF(1909,    DefaultValueBadParamType,       IDS_DefaultValueBadParamType)
ERRORDEF(1910,    DefaultValueBadValueType,       IDS_DefaultValueBadValueType)
WARNDEF( 1911, 1, NonVirtualCallFromClosure,      IDS_NonVirtualCallFromClosure)

// Errors in the range 2000-3000 are reserved for the command-line
ERRORDEF(2000,    InitError,                      IDS_INITERROR)
ERRORDEF(2001,    FileNotFound,                   IDS_FILENOTFOUND)
WARNDEF( 2002, 1, FileAlreadyIncluded,            IDS_FILEALREADYINCLUDED)
ERRORDEF(2003,    DuplicateResponseFile,          IDS_DUPLICATERESPONSEFILE)
ERRORDEF(2005,    NoFileSpec,                     IDS_NOFILESPEC)
ERRORDEF(2006,    SwitchNeedsString,              IDS_SWITCHNEEDSSTRING)
ERRORDEF(2007,    BadSwitch,                      IDS_BADSWITCH)
ERRORDEF(2008,    NoSources,                      IDS_NOSOURCES)
//ERRORDEF(2009,    BadOptions,                     IDS_BADOPTIONS)
//ERRORDEF(2010,    CompileFailed,                  IDS_COMPILEFAILED)
ERRORDEF(2011,    OpenResponseFile,               IDS_NORESPONSEFILE)
ERRORDEF(2012,    CantOpenFileWrite,              IDS_CANTOPENFILEWRITE)
ERRORDEF(2013,    BadBaseNumber,                  IDS_BADBASENUMBER)
WARNDEF( 2014, 1, UseNewSwitch,                   IDS_USENEWSWITCH)
ERRORDEF(2015,    BinaryFile,                     IDS_BINARYFILE)
FATALDEF(2016,    BadCodepage,                    IDS_BADCODEPAGE)
ERRORDEF(2017,    NoMainOnDLL,                    IDS_NOMAINONDLL)
FATALDEF(2018,    NoMessagesDLL,                  0)     // This one doesn't have a message in the message dll, because it would be moot!
FATALDEF(2019,    InvalidTarget,                  IDS_INVALIDTARGET)
ERRORDEF(2020,    BadTargetForSecondInputSet,     IDS_BADSECONDTARGET)
FATALDEF(2021,    InputFileNameTooLong,           IDS_InputFileNameTooLong)
ERRORDEF(2022,    NoSourcesInLastInputSet,        IDS_NoSourcesInLastInputSet)
WARNDEF( 2023, 1, NoConfigNotOnCommandLine,       IDS_NoConfigNotOnCommandLine)
ERRORDEF(2024,    BadFileAlignment,               IDS_BadFileAlignment)
//ERRORDEF(2025,    NoDebugSwitchPDBAltPath,        IDS_NoDebugSwitchPDBAltPath)
ERRORDEF(2026,    NoDebugSwitchSourceMap,         IDS_NoDebugSwitchSourceMap)
ERRORDEF(2027,    SourceMapFileBinary,            IDS_SourceMapFileBinary)
//ERRORDEF(2028,    CantOpenFileRead,               IDS_CANTOPENFILEREAD)
WARNDEF( 2029, 1, DefineIdentifierRequired,       IDS_DefineIdentifierRequired)
ERRORDEF(2030,    InvalidSourceMap,               IDS_InvalidSourceMap)
ERRORDEF(2031,    NoSourceMapFile,                IDS_NoSourceMapFile)
ERRORDEF(2032,    IllegalOptionChar,              IDS_IllegalOptionChar)
FATALDEF(2033,    OutputFileExists,               IDS_OutputFileExists)
ERRORDEF(2034,    OneAliasPerRefernce,            IDS_OneAliasPerRefernce)
ERRORDEF(2035,    SwitchNeedsNumber,              IDS_SwitchNeedsNumber)

// NOTE: Range 3000-3999 is reserved for CLS errors.  The compiler does special things
// with these errors, so don't use this range unless it's really a CLS error.
WARNDEF( 3000, 1, CLS_NoVarArgs,                  IDS_CLS_NoVarArgs)
WARNDEF( 3001, 1, CLS_BadArgType,                 IDS_CLS_BadArgType)
WARNDEF( 3002, 1, CLS_BadReturnType,              IDS_CLS_BadReturnType)
WARNDEF( 3003, 1, CLS_BadFieldPropType,           IDS_CLS_BadFieldPropType)
WARNDEF( 3004, 1, CLS_BadUnicode,                 IDS_CLS_BadUnicode)
WARNDEF( 3005, 1, CLS_BadIdentifierCase,          IDS_CLS_BadIdentifierCase)
WARNDEF( 3006, 1, CLS_OverloadRefOut,             IDS_CLS_OverloadRefOut)
WARNDEF( 3007, 1, CLS_OverloadUnnamed,            IDS_CLS_OverloadUnnamed)
WARNDEF( 3008, 1, CLS_BadIdentifier,              IDS_CLS_BadIdentifier)
WARNDEF( 3009, 1, CLS_BadBase,                    IDS_CLS_BadBase)
WARNDEF( 3010, 1, CLS_BadInterfaceMember,         IDS_CLS_BadInterfacemember)
WARNDEF( 3011, 1, CLS_NoAbstractMembers,          IDS_CLS_NoAbstractMembers)
WARNDEF( 3012, 1, CLS_NotOnModules,               IDS_CLS_NotOnModules)
WARNDEF( 3013, 1, CLS_ModuleMissingCLS,           IDS_CLS_ModuleMissingCLS)
WARNDEF( 3014, 1, CLS_AssemblyNotCLS,             IDS_CLS_AssemblyNotCLS)
WARNDEF( 3015, 1, CLS_BadAttributeType,           IDS_CLS_BadAttributeType)
WARNDEF( 3016, 1, CLS_ArrayArgumentToAttribute,   IDS_CLS_ArrayArgumentToAttribute)
WARNDEF( 3017, 1, CLS_NotOnModules2,              IDS_CLS_NotOnModules2)
WARNDEF( 3018, 1, CLS_IllegalTrueInFalse,         IDS_CLS_IllegalTrueInFalse)
WARNDEF( 3019, 2, CLS_MeaninglessOnPrivateType,   IDS_CLS_MeaninglessOnPrivateType)
WARNDEF( 3021, 2, CLS_AssemblyNotCLS2,            IDS_CLS_AssemblyNotCLS2)
WARNDEF( 3022, 1, CLS_MeaninglessOnParam,         IDS_CLS_MeaninglessOnParam)
WARNDEF( 3023, 1, CLS_MeaninglessOnReturn,        IDS_CLS_MeaninglessOnReturn)
WARNDEF( 3024, 1, CLS_BadTypeVar,                 IDS_CLS_BadTypeVar)
//WARNDEF( 3025, 1, CLS_BadPropAccessor,            IDS_CLS_BadPropAccessor)
WARNDEF( 3026, 1, CLS_VolatileField,              IDS_CLS_VolatileField)
WARNDEF( 3027, 1, CLS_BadInterface,               IDS_CLS_BadInterface)
// END of CLS errors

WARNDEF( 5000, 1, UnknownOption,                  IDS_UnknownOption)
ERRORDEF(5001,    NoEntryPoint,                   IDS_NoEntryPoint)


// NOTE: Range 6000-6999 is reserved for PreSharp
